// src/components/DndDataUploader.js
import React from "react";
import { db } from "../../firebase/firebaseConfig"; // Путь к вашему файлу с конфигурацией Firebase
import { collection, addDoc } from "firebase/firestore";

// Массив заклинаний (данные для загрузки)
const spells = [
  {
    "№": "1",
    title: "Acid Splash",
    titleRus: "Кислотный Всплеск",
    level: "0",
    ritual: "FALSE",
    castingTime: "Action",
    castingTimeRus: "Действие",
    rangeFt: "60",
    componentV: "TRUE",
    componentS: "TRUE",
    componentM: "",
    componentMRus: "",
    concentration: "FALSE",
    duration: "FALSE",
    durationRus: "Мгновенно",
    description:
      "You create an acid bubble at a point within range, where it explodes in a 5-foot-radius Sphere. Each creature in that Sphere must succeed on a Dexterity saving throw or take 1d6 Acid damage.",
    descriptionRus:
      "Вы бросаете кислотный шарик в точку в пределах дальности, где он взрывается сферой с радиусом 5 футов. Каждое существо в этой сфере должно преуспеть в спаброске Ловкости или получить 1к6 урона кислотой.",
    onHigherLevel:
      "The damage increases by 1d6 when you reach levels 5 (2d6), 11 (3d6), and 17 (4d6).",
    onHigherLevelRus:
      "Урон увеличивается на 1к6, когда вы достигаете 5 уровня (2к6), 11 уровня (3к6) и 17 уровня (4к6).",
    school: "Evocation",
    schoolRus: "Созидания",
    classBarbarian: "FALSE",
    classBard: "FALSE",
    classCleric: "FALSE",
    classDruid: "FALSE",
    classFighter: "FALSE",
    classMonk: "FALSE",
    classPaladin: "FALSE",
    classRanger: "FALSE",
    classRogue: "FALSE",
    classSorcerer: "TRUE",
    classWarlock: "FALSE",
    classWizard: "TRUE",
    dopMaterial: "",
  },
  {
    "№": "2",
    title: "Aid",
    titleRus: "(Подмога)",
    level: "2",
    ritual: "FALSE",
    castingTime: "Action",
    castingTimeRus: "Действие",
    rangeFt: "30",
    componentV: "TRUE",
    componentS: "TRUE",
    componentM: "a strip of white cloth",
    componentMRus: "полоска белой ткани",
    concentration: "FALSE",
    duration: "8 hours",
    durationRus: "8 часов",
    description:
      "Choose up to three creatures within range. Each target's Hit Point maximum and current Hit Points increase by 5 for the duration.",
    descriptionRus:
      "Выберите до 3 существ в пределах дистанции. На время длительности максимум хитов и текущие хиты всех целей увеличиваются на 5.",
    onHigherLevel:
      "Each target's Hit Points increase by 5 for each spell slot level above 2",
    onHigherLevelRus:
      "Хиты целей увеличиваются ещё на 5 за каждый уровень ячейки выше 2.",
    school: "Abjuration",
    schoolRus: "",
    classBarbarian: "FALSE",
    classBard: "TRUE",
    classCleric: "TRUE",
    classDruid: "TRUE",
    classFighter: "FALSE",
    classMonk: "FALSE",
    classPaladin: "TRUE",
    classRanger: "TRUE",
    classRogue: "FALSE",
    classSorcerer: "FALSE",
    classWarlock: "FALSE",
    classWizard: "FALSE",
    dopMaterial: "",
  },
  {
    "№": "3",
    title: "Alarm",
    titleRus: "Тревога",
    level: "1",
    ritual: "TRUE",
    castingTime: "1 minute or Ritual",
    castingTimeRus: "1 минута или ритуал",
    rangeFt: "30",
    componentV: "TRUE",
    componentS: "TRUE",
    componentM: "a bell and silver wire",
    componentMRus: "колокольчик и серебряная проволочка",
    concentration: "FALSE",
    duration: "8 hours",
    durationRus: "8 часов",
    description:
      "You set an alarm against intrusion. Choose a door, a window, or an area within range that is no larger than a 20-foot Cube. Until the spell ends, an alarm alerts you whenever a creature touches or enters the warded area. When you cast the spell, you can designate creatures that won't set off the alarm. You also choose whether the alarm is audible or mental:<br>\n<Strong>Audible Alarm.</strong> The alarm produces the sound of a handbell for 10 seconds within 60 feet of the warded area.<br>\n<Strong>Mental Alarm.</strong> You are alerted by a mental ping if you are within 1 mile of the warded area. This ping awakens you if you're asleep.",
    descriptionRus:
      "Вы устанавливаете сигнализацию на случай вторжения. Выберите дверь, окно или область в пределах дистанции не больше куба с длиной ребра 20 футов. До окончания действия заклинания тревога уведомляет вас каждый раз, когда существо входит или касается охраняемой области. При накладывании заклинания вы можете указать существ, которые не будут вызывать срабатывание тревоги. Вы также выбираете, будет тревога мысленной или звуковой.<br>\n<Strong>Звуковая.</Strong> Тревога издаёт звук колокольчика в течение 10 секунд в радиусе 60 футов от охраняемой области.<br>\n<Strong>Мысленная.</Strong> Вы получаете мысленный сигнал, если находитесь в радиусе 1 мили от охраняемой области. Этот сигнал будит вас, если вы спите.",
    onHigherLevel: "",
    onHigherLevelRus: "",
    school: "Abjuration",
    schoolRus: "",
    classBarbarian: "FALSE",
    classBard: "FALSE",
    classCleric: "FALSE",
    classDruid: "FALSE",
    classFighter: "FALSE",
    classMonk: "FALSE",
    classPaladin: "FALSE",
    classRanger: "TRUE",
    classRogue: "FALSE",
    classSorcerer: "FALSE",
    classWarlock: "FALSE",
    classWizard: "TRUE",
    dopMaterial: "",
  },
  {
    "№": "4",
    title: "Alter Self",
    titleRus: "Смена Обличья",
    level: "2",
    ritual: "FALSE",
    castingTime: "Action",
    castingTimeRus: "Действие",
    rangeFt: "Self",
    componentV: "TRUE",
    componentS: "TRUE",
    componentM: "",
    componentMRus: "",
    concentration: "TRUE",
    duration: "Concentration, up to 1 hour",
    durationRus: "Концентрация, до 1 часа",
    description:
      "You alter your physical form. Choose one of the following options. Its effects last for the duration, during which you can take a Magic action to replace the option you chose with a different one.<br>\n<strong>Aquatic Adaptation.</strong> You sprout gills and grow webs between your fingers. You can breathe underwater and gain a Swim Speed equal to your Speed.<br>\n<strong>Change Appearance.</strong> You alter your appearance. You decide what you look like, including your height, weight, facial features, sound of your voice, hair length, coloration, and other distinguishing characteristics. You can make yourself appear as a member of another species, though none of your statistics change. You can't appear as a creature of a different size, and your basic shape stays the same; if you're bipedal, you can't use this spell to become quadrupedal, for instance. For the duration, you can take a Magic action to change your appearance in this way again.<br>\n<strong>Natural Weapons.</strong> You grow claws (Slashing), fangs (Piercing), horns (Piercing), or hooves (Bludgeoning). When you use your Unarmed Strike to deal damage with that new growth, it deals ld6 damage of the type in parentheses instead of dealing the normal damage for your Unarmed Strike, and you use your spellcasting ability modifier for the attack and damage rolls rather than using Strength.",
    descriptionRus:
      "Вы принимаете другой облик. При накладывании выберите один из представленных ниже вариантов, эффект от которого будет длиться всю длительность заклинания. Пока заклинание активно, вы можете использовать действие магия, чтобы заменить выбранный вами эффект другим.<br>\n<strong>Адаптация к воде.</strong> Вы приспосабливаете своё тело к существованию в воде, отращивая жабры и перепонки между пальцами. Вы можете дышать под водой и получаете скорость плавания, равную вашей скорости.<br>\n<strong>Изменение внешности. </strong>Вы изменяете свою внешность. Вы решаете, как будете выглядеть, включая рост, вес, черты лица, звук голоса, длину волос, цвет и другие отличительные характеристики. Вы можете стать похожим на представителя другого вида, но ваши показатели не изменяются. Вы не можете стать существом другого размера, и ваша основная форма остаётся той же; например, если вы двуногий, вы не можете с помощью этого заклинания стать четвероногим. В течение действия заклинания вы можете совершить действие магия, чтобы снова изменить свою внешность таким образом.<br>\n<strong>Естественное оружие.</strong> Вы отращиваете когти (рубящий урон), клыки (колющий урон), рога (дробящий урон) или копыта (дробящий урон). При нанесении урона безоружным ударом вы наносите 1к6 дробящего, колющего или рубящего урона, в зависимости от выбранного вами оружия, и вы используете модификатор заклинательной характеристики для бросков атаки и урона вместо Силы.",
    onHigherLevel: "",
    onHigherLevelRus: "",
    school: "Transmutation",
    schoolRus: "Преображения",
    classBarbarian: "FALSE",
    classBard: "FALSE",
    classCleric: "FALSE",
    classDruid: "FALSE",
    classFighter: "FALSE",
    classMonk: "FALSE",
    classPaladin: "FALSE",
    classRanger: "FALSE",
    classRogue: "FALSE",
    classSorcerer: "TRUE",
    classWarlock: "FALSE",
    classWizard: "TRUE",
    dopMaterial: "",
  },
  {
    "№": "5",
    title: "Animal Friendship",
    titleRus: "Дружба С Животными",
    level: "1",
    ritual: "FALSE",
    castingTime: "Action",
    castingTimeRus: "Действие",
    rangeFt: "30",
    componentV: "TRUE",
    componentS: "TRUE",
    componentM: "a morsel of food",
    componentMRus: "кусочек пищи",
    concentration: "FALSE",
    duration: "24 hours",
    durationRus: "24 часа",
    description:
      "Target a Beast that you can see within range. The target must succeed on a Wisdom saving throw or\nhave the Charmed condition for the duration. If you or one of your allies deals damage to the target, the spells ends.",
    descriptionRus:
      "Целью заклинания становится существо с типом зверь, которое вы видите в пределах дистанции. Цель должна преуспеть в спасброске Мудрости, иначе она будет находиться под действием состояния очарованный на продолжительность действия заклинания. Если вы или один из ваших союзников наносит урон цели, то заклинание заканчивается.",
    onHigherLevel:
      "You can target one additional Beast for each spell slot level above 1.",
    onHigherLevelRus:
      "Вы можете выбрать одну дополнительную цель (зверя) за каждый уровень ячейки выше 1.",
    school: "Enchantment",
    schoolRus: "Очарования",
    classBarbarian: "FALSE",
    classBard: "TRUE",
    classCleric: "FALSE",
    classDruid: "TRUE",
    classFighter: "FALSE",
    classMonk: "FALSE",
    classPaladin: "FALSE",
    classRanger: "TRUE",
    classRogue: "FALSE",
    classSorcerer: "FALSE",
    classWarlock: "FALSE",
    classWizard: "FALSE",
    dopMaterial: "",
  },
  {
    "№": "6",
    title: "Animal Messenger",
    titleRus: "Почтовое Животное",
    level: "2",
    ritual: "TRUE",
    castingTime: "Action or Ritual",
    castingTimeRus: "Действие или ритуал",
    rangeFt: "30",
    componentV: "TRUE",
    componentS: "TRUE",
    componentM: "a morsel of food",
    componentMRus: "кусочек пищи",
    concentration: "FALSE",
    duration: "24 hours",
    durationRus: "24 часа",
    description:
      'A Tiny Beast of your choice that you can see within range must succeed on a Charisma saving throw, or it attempts to deliver a message for you (if the target\'s Challenge Rating isn\'t 0, it automatically succeeds). You specify a location you have visited and a recipient who matches a general description, such as ""a person dressed in the uniform of the town guard"" or ""a red-haired dwarf wearing a pointed hat."" You also communicate a message of up to twenty-five words. The Beast travels for the duration toward the specified location, covering about 25 miles per 24 hours or 50 miles if the Beast can fly.<br>\nWhen the Beast arrives, it delivers your message to the creature that you described, mimicking your communication. If the Beast doesn\'t reach its destination before the spell ends, the message is lost, and the Beast returns to where you cast the spell.',
    descriptionRus:
      "Крохотный зверь на ваш выбор, которого вы видите в пределах дистанции, должен преуспеть в спасброске Харизмы, иначе он попытается доставить ваше сообщение (если ПО цели не 0, то она автоматически преуспевает в спасброске). Вы указываете место, которое когда-то уже посещали, и получателя, описывая его признаки, такие как «персона в униформе городской стражи» или «рыжий дварф в остроконечной шляпе». Вы также произносите сообщение длиной не более 25 слов. Зверь в течение длительности заклинания двигается в указанное место, покрывая примерно 50 миль за 24 часа при полёте или 25 миль при других видах перемещения.<br>\nПрибыв на место, зверь передаёт ваше сообщение описанному вами существу, изображая звук вашего голоса. Если зверь не достигнет места до окончания действия заклинания, то сообщение будет утеряно, а зверь начнёт возвращаться к тому месту, где вы наложили на него заклинание.",
    onHigherLevel:
      "The spell's duration increases by 48 hours for each spell slot level above 2.",
    onHigherLevelRus:
      "Длительность увеличивается на 48 часов за каждый уровень ячейки выше 2.",
    school: "Enchantment",
    schoolRus: "Очарования",
    classBarbarian: "FALSE",
    classBard: "TRUE",
    classCleric: "FALSE",
    classDruid: "TRUE",
    classFighter: "FALSE",
    classMonk: "FALSE",
    classPaladin: "FALSE",
    classRanger: "TRUE",
    classRogue: "FALSE",
    classSorcerer: "FALSE",
    classWarlock: "FALSE",
    classWizard: "FALSE",
    dopMaterial: "",
  },
  {
    "№": "7",
    title: "Animal Shapes",
    titleRus: "Превращение в животных",
    level: "8",
    ritual: "FALSE",
    castingTime: "Action",
    castingTimeRus: "Действие",
    rangeFt: "30",
    componentV: "TRUE",
    componentS: "TRUE",
    componentM: "",
    componentMRus: "",
    concentration: "FALSE",
    duration: "24 hours",
    durationRus: "24 часа",
    description:
      "Choose any number of willing creatures that you can see within range. Each target shape-shifts into a Large or smaller Beast of your choice that has a Challenge Rating of 4 or lower. You can choose a different form for each target. On later turns, you can take a Magic action to transform the targets again.<br>\nA target's game statistics are replaced by the chosen Beast's statistics, but the target retains its creature type; Hit Points; Hit Point Dice; alignment; ability to communicate; and Intelligence, Wisdom,and Charisma scores. The target's actions are limited by the Beast form's anatomy, and it can't cast spells. The target's equipment melds into the new form, and the target can't use any of that equipment while in that form.<br>\nThe target gains a number of Temporary Hit Points equal to the Beast form's Hit Points. The transformation lasts for the duration for each target, until the target has no Temporary Hit Points, or until the target leaves the form as a Bonus Action.",
    descriptionRus:
      "Выберите любое число согласных существ, которых видите в пределах дистанции. Вы превращаете каждую цель в зверя большого или меньше размера с показателем опасности не больше 4. Вы можете выбрать разных зверей для каждой цели. В последующие ходы вы можете использовать магическое действие, чтобы снова превратить цели. <br>\nСтатблок цели заменяется статблоком зверя, но цель сохраняет свой тип существа; количество хитов; кость хитов; мировоззрение; способность говорить; а также значения интеллекта мудрости и харизмы. Действия цели ограничены анатомией формы зверя и она не может накладывать заклинания. Снаряжение цели сливается с новой формой и цель не может использовать это снаряжение, находясь в этой форме.<br>\nЦель получает количество временных хитов, равно количеству хитов зверя. Превращение длится в течение указанного времени, пока у цели есть временные хиты, или пока цель не выйдет из этой формы бонусным действием.",
    onHigherLevel: "",
    onHigherLevelRus: "",
    school: "Transmutation",
    schoolRus: "Преображения",
    classBarbarian: "FALSE",
    classBard: "FALSE",
    classCleric: "FALSE",
    classDruid: "TRUE",
    classFighter: "FALSE",
    classMonk: "FALSE",
    classPaladin: "FALSE",
    classRanger: "FALSE",
    classRogue: "FALSE",
    classSorcerer: "FALSE",
    classWarlock: "FALSE",
    classWizard: "FALSE",
    dopMaterial: "",
  },
  {
    "№": "8",
    title: "Animate Dead",
    titleRus: "Оживление мертвецов",
    level: "3",
    ritual: "FALSE",
    castingTime: "1 minute",
    castingTimeRus: "1минута",
    rangeFt: "10",
    componentV: "TRUE",
    componentS: "TRUE",
    componentM: "a drop of blood, a piece of\nflesh, and a pinch of bone dust",
    componentMRus: "капля крови, кусочек плоти и щепотка\nкостной пыли",
    concentration: "FALSE",
    duration: "Instantaneous",
    durationRus: "Мгновенно",
    description:
      "Choose a pile of bones or a corpse of a Medium or Small Humanoid within range. The target becomes an Undead creature: a Skeleton if you chose bones or a Zombie if you chose a corpse (see appendix B for the stat blocks).<br>\nOn each of your turns, you can take a Bonus Action to mentally command any creature you made with this spell if the creature is within 60 feet of you (if you control multiple creatures, you can command any of them at the same time, issuing the same command to each one). You decide what action the creature will take and where it will move on its next turn, or you can issue a general command, such as to guard a chamber or corridor. If you issue no commands, the creature takes the\nDodge action and moves only to avoid harm. Once given an order, the creature continues to follow it until its task is complete. <br>\nThe creature is under your control for 24 hours, after which it stops obeying any command you'vegiven it. To maintain control of the creature for another 24 hours, you must cast this spell on the creature again before the current 24-hour period ends.<br>\nThis use of the spell reasserts your control over up to four creatures you have animated with this spell rather than animating a new creature.",
    descriptionRus:
      "Выберите груду костей или труп гуманоида среднего или маленького размера в пределах дистанции. Цель становится нежитью: скелетом, если вы выбрали кости, или зомби, если вы выбрали труп (см. приложение Б для статблоков).<br>\nВ каждый ваш ход вы можете бонусным действием мысленно приказать существу, созданному этим заклинанием, если оно находится в пределах 60 футов от вас (если вы контролируете несколько существ, то вы можете отдавать один и тот же приказ любому количеству из них одновременно). Вы решаете, какое действие совершит это существо, и куда оно переместится в свой следующий ход, или вы можете отдать общий приказ, например, охранять комнату или коридор. Если вы не отдадите команду, то существо выполняет действие уклонение и перемещается только для того, чтобы избежать вреда. Получив приказ, существо продолжает его выполнять, пока задача не будет завершена.<br>\nСущество находится под вашим контролем 24 часа, после чего перестаёт слушаться команд. Для поддержания контроля ещё на 24 часа вы должны наложить это заклинание на него ещё раз до окончания 24-часового периода. <br>Такое наложение заклинания только поддерживает контроль над уже созданными существами, количество которых не может быть больше 4, и не оживляет новых.",
    onHigherLevel:
      "You animate or reassert control over two additional Undead creatures for each spell slot level above 3. Each of the creatures must come from a different corpse or pile of bones.",
    onHigherLevelRus:
      "Вы оживляете или продлеваете контроль над 2 дополнительными существами за каждый уровень ячейки выше 3. Для каждого создаваемого существа требуется отдельная куча костей или труп.",
    school: "Necrnmancy",
    schoolRus: "Некромантия",
    classBarbarian: "FALSE",
    classBard: "FALSE",
    classCleric: "TRUE",
    classDruid: "FALSE",
    classFighter: "FALSE",
    classMonk: "FALSE",
    classPaladin: "FALSE",
    classRanger: "FALSE",
    classRogue: "FALSE",
    classSorcerer: "FALSE",
    classWarlock: "FALSE",
    classWizard: "TRUE",
    dopMaterial: "",
  },
  {
    "№": "9",
    title: "Animate Objects",
    titleRus: "Оживление вещей",
    level: "5",
    ritual: "FALSE",
    castingTime: "Action",
    castingTimeRus: "Действие",
    rangeFt: "120",
    componentV: "TRUE",
    componentS: "TRUE",
    componentM: "",
    componentMRus: "",
    concentration: "TRUE",
    duration: "Concentration, up to 1 minute",
    durationRus: "Концентрация, до 1 минуты",
    description:
      "Objects animate at your command. Choose a number of nonmagical objects within range that aren't being worn or carried, aren't fixed to a surface, and aren't Gargantuan. The maximum number of objects is equal to your spellcasting aibility modifier; for this number, a Medium o r smaller target counts as one object, a Large target counts as two, and a Huge target counts as three.<br>\nEach target animates, sprouts legs, and becomes a Construct that uses the <strong>Animated Object</strong> stat block; this creature is under your control until the spell ends or until it is reduced to O Hit Points. Each creature you make with this spell is an ally to you and your allies. In combat, it shares your Initiative count and takes its turn immediately after yours.<br>\nUntil the speII ends, you can take a Bonus Action to mentally command any creature you made with this spell if the creature is within 500 feet of you (if you control multiple creatures, you can command any of them at the same time, issuing the same command to each one). If you issue no commands, the creature takes the Dodge action and moves only to avoid harm. When the creature drops to O Hit Points, it reverts to its object form, and any remaining damage carries over to that form.",
    descriptionRus:
      "По вашему приказу оживают предметы. Выберите несколько немагических предметов в пределах дистанции, которые никто не несёт и не носит, которые не прикреплены к поверхности, и не громадные. Максимальное количество предметов равно модификатору вашей заклинательной характеристики. Для этого количества, средний или меньше предмет считается за 1, большой предмет считается за 2, а огромный предмет считается за 3.<br>\nВсе цели оживают, у них вырастают ноги, и они становятся конструктами, которые используют статблок Оживлённого предмета (см. далее). Эти существа находятся под вашим контролем пока это заклинание активно или пока их хиты не уменьшатся до 0. Каждое существо, которое вы оживили этим заклинанием, является союзником для вас и ваших союзников. В бою оно разделяет вашу инициативу и совершает свой ход сразу после вас.<br>\nПока это заклинание активно, вы можете бонусным действием мысленно отдать приказ существу, которое оживили этим заклинанием, если оно находится в пределах 500 футов от вас (если вы контролируете несколько существ, то вы можете отдавать один и тот же приказ любому количеству из них одновременно). Если вы не отдадите команду, то существо будет использовать действие уклонение и двигаться только чтобы избежать вреда. Когда хиты существа опускаются до 0, оно возвращается в форму предмета, и оставшийся урон переносится на эту форму.",
    onHigherLevel:
      "The creature's Slam damage increases by 1d4 (Medium or smaller), 1d6 (Large), or 1d12 (Huge) for each spell slot level above 5.",
    onHigherLevelRus:
      "Урон атаки Удар увеличивается на 1к4 (у среднего существа и меньше), 1к6 (у большого существа) или 1к12 (у огромного существа) за каждый уровень ячейки выше 5.",
    school: "Transmutation",
    schoolRus: "Преображения",
    classBarbarian: "FALSE",
    classBard: "TRUE",
    classCleric: "FALSE",
    classDruid: "FALSE",
    classFighter: "FALSE",
    classMonk: "FALSE",
    classPaladin: "FALSE",
    classRanger: "FALSE",
    classRogue: "FALSE",
    classSorcerer: "TRUE",
    classWarlock: "FALSE",
    classWizard: "TRUE",
    dopMaterial: "animated object card",
  },
  {
    "№": "10",
    title: "Antilife Shell",
    titleRus: "Преграда жизни",
    level: "5",
    ritual: "FALSE",
    castingTime: "Action",
    castingTimeRus: "Действие",
    rangeFt: "Self",
    componentV: "TRUE",
    componentS: "TRUE",
    componentM: "",
    componentMRus: "",
    concentration: "TRUE",
    duration: "Concentration, up to 1 hour",
    durationRus: "Концентрация, до 1 часа",
    description:
      "An aura extends from you in a 10-foot Emanation for the duration. The aura prevents creatures other\nthan Constructs and Undead from passing or reaching through it. An affected creature can cast spells or make attacks with Ranged or Reach weapons through the barrier.<br>\nIf you move so that an affected creature is forced to pass through the barrier, the spell ends.",
    descriptionRus:
      "Аура распространяется от вас в пределах 10-футовой эманации на всю длительность заклинания. Аура не позволяет существам, кроме конструктов и нежити,\nпроникнуть внутрь полностью или частично. Подвергшееся воздействию существо может использовать заклинания или совершать атаки дальнобойным оружием или оружием со свойством досягаемость через барьер.<br>\nЕсли вы перемещаетесь так, что существо под воздействием заклинания вынуждено пройти сквозь барьер, то заклинание заканчивается.",
    onHigherLevel: "",
    onHigherLevelRus: "",
    school: "Abjuration",
    schoolRus: "",
    classBarbarian: "FALSE",
    classBard: "FALSE",
    classCleric: "FALSE",
    classDruid: "TRUE",
    classFighter: "FALSE",
    classMonk: "FALSE",
    classPaladin: "FALSE",
    classRanger: "FALSE",
    classRogue: "FALSE",
    classSorcerer: "FALSE",
    classWarlock: "FALSE",
    classWizard: "FALSE",
    dopMaterial: "",
  },
  {
    "№": "11",
    title: "Antimagic Field",
    titleRus: "Поле антимагии",
    level: "8",
    ritual: "FALSE",
    castingTime: "Action",
    castingTimeRus: "Действие",
    rangeFt: "Self",
    componentV: "TRUE",
    componentS: "TRUE",
    componentM: "железные опилки",
    componentMRus: "железная стружка",
    concentration: "TRUE",
    duration: "Concentration, up to 1 hour",
    durationRus: "Концентрация, до 1 часа",
    description:
      "An aura of antimagic surrounds you in 10-foot Emanation. No one can cast spells, take Magic actions, or create other magical effects inside the aura, and those things can't target or otherwise affect anything inside it. Magical properties of magic items don't work inside the aura or on anything inside it.<br>\nAreas of effect created by spells or other magic can't extend into the aura, and no one can teleport\ninto or out of it or use planar travel there. Portals close temporarily while in the aura.<br>\nOngoing spells, except those cast by an Artifact or a deity, are suppressed in the area. While an effect is suppressed, it doesn't function, but the time it spends suppressed counts against its duration.<br>\nDispel Magic has no effect on the aura, and the auras created by different Antimagic Field spells don't nullify each other.",
    descriptionRus:
      "Аура 10-футовой эманации антимагии окружает вас. Никто не может накладывать заклинания, совершать действия магия или создавать другие магические эффекты внутри ауры. Всё это не может нацеливаться на что-либо внутри ауры или каким-либо образом воздействовать на неё. Магические свойства магических предметов не работают внутри ауры или на что-либо внутри неё. <br>\nОбласти эффектов, создаваемые заклинаниями или другой магией, не могут распространяться внутрь ауры, и никто не может телепортироваться в неё или из неё, а также перемещаться из других планов. Порталы временно закрываются, находясь в ауре.<br>\nДействующие заклинания, за исключением тех, что были наложены артефактом или божеством, подавляются в этой области. Пока эффект подавлен, он не функционирует, но время его подавления засчитывается в его длительность. <br>\nЗаклинание Рассеивание магии не оказывает влияния на ауру, и ауры, созданные разными заклинаниями Поле антимагии, не нейтрализуют друг друга.",
    onHigherLevel: "",
    onHigherLevelRus: "",
    school: "Abjuration",
    schoolRus: "",
    classBarbarian: "FALSE",
    classBard: "FALSE",
    classCleric: "TRUE",
    classDruid: "FALSE",
    classFighter: "FALSE",
    classMonk: "FALSE",
    classPaladin: "FALSE",
    classRanger: "FALSE",
    classRogue: "FALSE",
    classSorcerer: "FALSE",
    classWarlock: "FALSE",
    classWizard: "TRUE",
    dopMaterial: "",
  },
  {
    "№": "12",
    title: "Antipathy/Sympathy",
    titleRus: "Антипатия/Симпатия",
    level: "8",
    ritual: "FALSE",
    castingTime: "1 hour",
    castingTimeRus: "1 час",
    rangeFt: "60",
    componentV: "TRUE",
    componentS: "TRUE",
    componentM: "a mix of vinegar and honey",
    componentMRus: "смесь уксуса и мёда",
    concentration: "FALSE",
    duration: "10 days",
    durationRus: "10 дней",
    description:
      "As you cast the spell, choose whether it creates antipathy or sympathy, and target one creature or object that is Huge or smaller. Then specify a kind of creature, such as red dragons, goblins, or vampires.<br>\nA creature of the chosen kind makes a Wisdom saving throw when it comes within 120 feet of the target. Your choice of antipathy or sympathy determines what happens to a creature when it fails that save: <br><br>\n<strong>Antipathy.<strong/> The creature has the Frightened condition. The Frightened creature must use its movement on its turns to get as far away as possible from the target, moving by the safest route.<br>\n<strong>Sympathy</strong>. The creature has the Charmed condition. The Charmed creature must use its movement on its turns to get as close as possible to the target, moving by the safest route. If the creature is within 5 feet of the target, the creature can't willingly move away. If the target damages the Charmed creature, that creature can make a Wisdom saving throw to end the effect, as described below.<br><br>\n<strong>Ending the Effect.</strong> If the Frightened or Charmed creature ends its turn more than 120 feet away from the target, the creature makes a Wisdom saving throw. On a successful save, the creature is no longer affected by the target. A creature that successfully saves against this effect is immune to it for 1 minute, after which it can be affected again.",
    descriptionRus:
      "Когда вы накладываете это заклинание, то выберите, будет ли оно создавать антипатию или симпатию, и выберите 1 цель, которая является существом или объектом размером не больше огромного. Затем укажите вид существа, например, красных драконов, гоблинов или вампиров. <br>\nСущество выбранного вида совершает спасбросок Мудрости, когда оказывается в пределах 120 футов от цели. Ваш выбор антипатии или симпатии определяет, что произойдёт с существом, если оно провалит этот спасбросок:<br><br>\n<strong>Антипатия.</strong> Существо получает состояние испуганный. Испуганное существо должно использовать своё перемещение в свой ход, чтобы как можно быстрее отдалиться от цели, двигаясь по самому безопасному маршруту.<br>\n<strong>Симпатия.</strong> Существо получает состояние очарованный. Очарованное существо должно использовать своё перемещение в каждый свой ход, чтобы как можно ближе приблизиться к цели, двигаясь по самому безопасному маршруту. Если существо находится в пределах 5 футов от цели, то оно не может добровольно отойти от неё. Если цель наносит урон очарованному существу, то это существо может совершить спасбросок Мудрости, чтобы прекратить действие эффекта, как описано ниже.<br><br>\n<strong>Окончание эффекта.</strong> Если испуганное или очарованное существо заканчивает свой ход на расстоянии более 120 футов от цели, то оно совершает спасбросок Мудрости. При успешном спасброске существо больше не подвержено воздействию цели. Существо, успешно прошедшее спасбросок против этого эффекта, становится невосприимчивым к нему на 1 минуту, после чего снова может подвергнуться воздействию.",
    onHigherLevel: "",
    onHigherLevelRus: "",
    school: "Enchantment",
    schoolRus: "Очарования",
    classBarbarian: "FALSE",
    classBard: "TRUE",
    classCleric: "FALSE",
    classDruid: "TRUE",
    classFighter: "FALSE",
    classMonk: "FALSE",
    classPaladin: "FALSE",
    classRanger: "FALSE",
    classRogue: "FALSE",
    classSorcerer: "FALSE",
    classWarlock: "FALSE",
    classWizard: "TRUE",
    dopMaterial: "",
  },
  {
    "№": "13",
    title: "Arcane Eye",
    titleRus: "Магичесчкий глаз",
    level: "4",
    ritual: "FALSE",
    castingTime: "Action",
    castingTimeRus: "Действие",
    rangeFt: "30",
    componentV: "TRUE",
    componentS: "TRUE",
    componentM: "a bit of bat fur",
    componentMRus: "мех летучей мыши",
    concentration: "TRUE",
    duration: "Concentration, up to 1 hour",
    durationRus: "Концентрация, до 1 часа",
    description:
      "You create an Invisible, invulnerable eye within range that hovers for the duration. You mentally receive visual information from the eye, which can see in every direction. It also has Darkvision with a range of 30 feet.<br>\nAs a Bonus Action, you can move the eye up to 30 feet in any direction. A solid barrier blocks the eye's movement, but the eye can pass through an opening as small as 1 inch in diameter.",
    descriptionRus:
      "Вы создаёте невидимый неуязвимый магический глаз в пределах дистанции, который парит в воздухе на время длительности. Вы мысленно воспринимаете зрительную информацию с глаза, у которого обычное зрение и тёмное зрение в пределах 30 футов. Глаз смотрит во всех направлениях.<br>\nВы можете бонусным действием переместить глаз на 30 футов в любом направлении. Глаз может удаляться от вас на любое расстояние, но не может уходить на другие планы существования. Сплошные препятствия блокируют движение глаза, но он может проходить через отверстия диаметром не менее 1 дюйма (2,5 сантиметра).",
    onHigherLevel: "",
    onHigherLevelRus: "",
    school: "Divination",
    schoolRus: "Прорицание",
    classBarbarian: "FALSE",
    classBard: "FALSE",
    classCleric: "FALSE",
    classDruid: "FALSE",
    classFighter: "FALSE",
    classMonk: "FALSE",
    classPaladin: "FALSE",
    classRanger: "FALSE",
    classRogue: "FALSE",
    classSorcerer: "FALSE",
    classWarlock: "FALSE",
    classWizard: "TRUE",
    dopMaterial: "",
  },
  {
    "№": "14",
    title: "Arcane Gate",
    titleRus: "Магические врата",
    level: "6",
    ritual: "FALSE",
    castingTime: "Action",
    castingTimeRus: "Действие",
    rangeFt: "500",
    componentV: "TRUE",
    componentS: "TRUE",
    componentM: "",
    componentMRus: "",
    concentration: "TRUE",
    duration: "Concentration , up to 10 minutes",
    durationRus: "Концентрация, до 10 минут",
    description:
      "You create linked teleportation portals. Choose two Large, unoccupied spaces on the ground that you can see, one space within range and the other one within 10 feet of you. A circular portal opens in each of those spaces and remains for the duration.<br>\nThe portals are two-dimensional glowing rings filled with mist that blocks sight. They hover inches from the ground and are perpendicular to it.<br>\nA portal is open on only one side (you choose which). Anything entering the open side of a portal exits from the open side of the other portal as if the two were adjacent to each other. As a Bonus Action you can change the facing of the open sides.",
    descriptionRus:
      "Вы создаёте связанные порталы для телепортации. Выберите две точки на земле, которые вы видите, одну в пределах 10 футов от себя, и вторую в пределах дистанции. В каждой точке открывается круглый портал, который остаётся на время длительности.<br>\nПорталы представляют собой двумерные светящиеся кольца, заполненные туманом, который блокирует видимость. Они парят в нескольких дюймах над землёй и расположены перпендикулярно ей.<br>\nКаждый портал открыт только с одной стороны (вы выбираете, с какой). Всё, что входит в открытую сторону портала, выходит из открытой стороны другого портала, как если бы эти два пространства находились рядом друг с другом. Вы можете изменить направление открытых сторон бонусным действием.",
    onHigherLevel: "",
    onHigherLevelRus: "",
    school: "Conjuration",
    schoolRus: "",
    classBarbarian: "FALSE",
    classBard: "FALSE",
    classCleric: "FALSE",
    classDruid: "FALSE",
    classFighter: "FALSE",
    classMonk: "FALSE",
    classPaladin: "FALSE",
    classRanger: "FALSE",
    classRogue: "FALSE",
    classSorcerer: "TRUE",
    classWarlock: "TRUE",
    classWizard: "TRUE",
    dopMaterial: "",
  },
  {
    "№": "15",
    title: "Arcane Lock",
    titleRus: "Волшебный замок",
    level: "2",
    ritual: "FALSE",
    castingTime: "Action",
    castingTimeRus: "Действие",
    rangeFt: "Touch",
    componentV: "TRUE",
    componentS: "TRUE",
    componentM: "gold dust worth 25+ GP, which\nthe spell consumes",
    componentMRus: "золотая пыль стоимостью 25+ зм, расходуемая заклинанием",
    concentration: "FALSE",
    duration: "Until dispelled",
    durationRus: "Пока не рассеется",
    description:
      "You touch a closed door, window, gate, container, or hatch and magically lock it for the duration. This lock can't be unlocked by any nonmagical means. You and any creatures you designate when you cast the spell can open and close the object despite the lock. You can also set a password that, when spoken within 5 feet of the object, unlocks it for 1 minute.",
    descriptionRus:
      "Вы касаетесь закрытой двери, окна, ворот, контейнера или люка и магически запираете его на время длительности. Этот замок нельзя открыть немагическими способами. Вы и любые существа, которых вы выбираете при наложении заклинания, можете открывать и закрывать объект, несмотря на замок. Вы также можете установить пароль, который, будучи произнесён в пределах 5 футов от объекта, откроет его на 1 минуту.",
    onHigherLevel: "",
    onHigherLevelRus: "",
    school: "Abjuration",
    schoolRus: "",
    classBarbarian: "FALSE",
    classBard: "FALSE",
    classCleric: "FALSE",
    classDruid: "FALSE",
    classFighter: "FALSE",
    classMonk: "FALSE",
    classPaladin: "FALSE",
    classRanger: "FALSE",
    classRogue: "FALSE",
    classSorcerer: "FALSE",
    classWarlock: "FALSE",
    classWizard: "TRUE",
    dopMaterial: "",
  },
  {
    "№": "16",
    title: "Arcane Vigor",
    titleRus: "Магическая энергия",
    level: "2",
    ritual: "FALSE",
    castingTime: "Bonus Action",
    castingTimeRus: "Бонусное Действие",
    rangeFt: "Self",
    componentV: "TRUE",
    componentS: "TRUE",
    componentM: "",
    componentMRus: "",
    concentration: "FALSE",
    duration: "Instantaneous",
    durationRus: "Мгновенная",
    description:
      "You tap into your life force to heal yourself. Roll one or two of your unexpended Hit Point Dice, and regain a number of Hit Points equal to the rail's total plus your spellcasting ability modifier. Those dice are then expended.",
    descriptionRus:
      "Вы используете свою жизненную силу для исцеления себя. Бросьте 1 или 2 неиспользованные кости хитов и восстановите количество хитов, равное сумме выпавших значений и вашему модификатору характеристики заклинателя. Эти кости затем считаются использованными.",
    onHigherLevel:
      "The number of unexpended Hit Dice you can roll increases by one for each spell slot level above 2.",
    onHigherLevelRus:
      "Количество неиспользованных костей хитов, которые вы можете бросить, увеличивается на 1 за каждый уровень ячейки выше 2.",
    school: "Abjuration",
    schoolRus: "",
    classBarbarian: "FALSE",
    classBard: "FALSE",
    classCleric: "FALSE",
    classDruid: "FALSE",
    classFighter: "FALSE",
    classMonk: "FALSE",
    classPaladin: "FALSE",
    classRanger: "FALSE",
    classRogue: "FALSE",
    classSorcerer: "TRUE",
    classWarlock: "FALSE",
    classWizard: "TRUE",
    dopMaterial: "",
  },
  {
    "№": "17",
    title: "Armor of Agathys",
    titleRus: "Доспехи Агатиса",
    level: "1",
    ritual: "FALSE",
    castingTime: "Bonus Action",
    castingTimeRus: "Бонусное Действие",
    rangeFt: "Self",
    componentV: "TRUE",
    componentS: "TRUE",
    componentM: "a shard of blue glass",
    componentMRus: "осколок синего стекла",
    concentration: "FALSE",
    duration: "1 hour",
    durationRus: "1 час",
    description:
      "Protective magical frost surrounds you. You gain 5 Temporary Hit Points. If a creature hits you with a melee attack roll before the spell ends, the creature takes 5 Cold damage. The spell ends early if you have no Temporary Hit Points.",
    descriptionRus:
      "Вас окружает магический защитный иней. Вы получаете 5 временных хитов. Если существо атакует вас рукопашной атакой до того, как заклинание завершится, то оно получает 5 урона холодом. Заклинание заканчивается раньше, если у вас не осталось временных хитов.",
    onHigherLevel:
      "The Temporary Hit Points and the Cold damage both increase by 5 for each spell slot level above 1.",
    onHigherLevelRus:
      "Временные хиты и урон холодом увеличиваются на 5 за каждый уровень ячейки выше 1.",
    school: "Abjuration",
    schoolRus: "",
    classBarbarian: "FALSE",
    classBard: "FALSE",
    classCleric: "FALSE",
    classDruid: "FALSE",
    classFighter: "FALSE",
    classMonk: "FALSE",
    classPaladin: "FALSE",
    classRanger: "FALSE",
    classRogue: "FALSE",
    classSorcerer: "FALSE",
    classWarlock: "TRUE",
    classWizard: "FALSE",
    dopMaterial: "",
  },
  {
    "№": "18",
    title: "Arms of Hadar",
    titleRus: "Руки Хадара",
    level: "1",
    ritual: "FALSE",
    castingTime: "Action",
    castingTimeRus: "Действие",
    rangeFt: "Self",
    componentV: "TRUE",
    componentS: "TRUE",
    componentM: "",
    componentMRus: "",
    concentration: "FALSE",
    duration: "Instantaneous",
    durationRus: "Мгновенная",
    description:
      "Invoking Hadar, you cause tendrils to erupt from yourself. Each creature in a 10-foot Emanation originating from you makes a Strength saving throw. On a failed save a target takes 2d6 Necrotic damage and can't take Reactions until the start of its next turn. On a successful save, a target takes half as much damage only.",
    descriptionRus:
      "Вы взываете к мощи Хадара, заставляя отростки вырваться из вас. Каждое существо в 10-футовой эманации, исходящей от вас, совершает спасбросок Силы. В случае провала цели получают 2к6 урона некротической энергией и до следующего своего хода не могут совершать реакции. В случае успеха существа получают половину урона.",
    onHigherLevel:
      "The damage increases by ld6 for each spell slot level above 1.",
    onHigherLevelRus:
      "Урон увеличивается на 1к6 за каждый уровень ячейки заклинаний выше 1.",
    school: "Conjuration",
    schoolRus: "",
    classBarbarian: "FALSE",
    classBard: "FALSE",
    classCleric: "FALSE",
    classDruid: "FALSE",
    classFighter: "FALSE",
    classMonk: "FALSE",
    classPaladin: "FALSE",
    classRanger: "FALSE",
    classRogue: "FALSE",
    classSorcerer: "FALSE",
    classWarlock: "TRUE",
    classWizard: "FALSE",
    dopMaterial: "",
  },
  {
    "№": "19",
    title: "Astral Projection",
    titleRus: "Проекция в Астрал",
    level: "9",
    ritual: "FALSE",
    castingTime: "1 hour",
    castingTimeRus: "1 час",
    rangeFt: "10",
    componentV: "TRUE",
    componentS: "TRUE",
    componentM:
      "for each of the spell's targets, one jacinth worth 7,000+ GP and one silver bar worth 100+ GP, all of which the spell consumes",
    componentMRus:
      "для каждой цели заклинания требуется по одному гиацинту стоимостью 1000+ зм и по одному слитку серебра стоимостью 100+ зм; все компоненты расходуются заклинанием",
    concentration: "FALSE",
    duration: "Until dispelled",
    durationRus: "Пока не рассеется",
    description:
      "You and up to eight willing creatures within range project your astral bodies into the Astral Plane (the spell ends instantly if you are already on that plane). Each target's body is left behind in a state of suspended animation; it has the Unconscious condition, doesn't need food or air, and doesn't age.<br>\nA target's astral form resembles its body in almost every way, replicating its game statistics and possessions. The. principal difference is the addition of a silvery cord that trails from between the shoulder blades of the astral form. The cord fades from view after 1 foot. If the cord is cut-which happens only when an effect states that it does so-the target's body and astral form both die.<br>\nA target's astral form can travel through the Astral Plane. The moment an astral form leaves that plane, the target's body and possessions travel along the silver cord, causing the target to re-enter its body on the new plane.<br>\nAny damage or other effects that apply to an astral form have no effect on the target's body and vice versa. If a target's body or astral form drops to 0 Hit Points, the spell ends for that target. The spell ends for all the targets if you take a Magic action to dismiss it.<br>\nWhen the spell ends for a target who isn't dead, the target reappears in its body and exits the state of suspended animation.",
    descriptionRus:
      "Вы и до 8 согласных существ в пределах дальности заклинания проецируете свои астральные тела на Астральный план (заклинание немедленно оканчивается, если вы уже находитесь на этом плане). Оставленные тела находятся в анабиозе; они получают состояние бессознательный, не нуждаются в пище или воздухе и не стареют.<br>\nАстральная форма цели напоминает её тело почти во всех отношениях, воспроизводя её статблок и снаряжение. Единственным отличием является серебряная нить, исходящая у вас между лопаток и торчащая наружу, становясь невидимой через 1 фут. Эта нить связывает цель с материальным телом. Если нить перерезать (что происходит только в том случае, если эффект это предусматривает), то тело цели и её астральная форма умирают.<br>\nАстральная форма цели может перемещаться по Астральному плану. В тот момент, когда астральная форма покидает этот план, тело цели и снаряжение переносятся по серебряной нити, заставляя вернуться в своё тело при входе на другой план.<br>\nЛюбой урон или другие эффекты, применяемые к астральной форме, не оказывают воздействия на тело цели, и наоборот. Если тело или астральная форма цели теряют все хиты, то заклинание заканчивается для этой цели. Заклинание заканчивается для всех целей, если вы совершаете действие магия, чтобы развеять его.<br>\nКогда заклинание заканчивается для цели, которая не мертва, то она вновь появляется в своём теле и выходит из анабиоза.",
    onHigherLevel: "",
    onHigherLevelRus: "",
    school: "Necrnmancy",
    schoolRus: "Некромантия",
    classBarbarian: "FALSE",
    classBard: "FALSE",
    classCleric: "TRUE",
    classDruid: "FALSE",
    classFighter: "FALSE",
    classMonk: "FALSE",
    classPaladin: "FALSE",
    classRanger: "FALSE",
    classRogue: "FALSE",
    classSorcerer: "FALSE",
    classWarlock: "TRUE",
    classWizard: "TRUE",
    dopMaterial: "",
  },
  {
    "№": "20",
    title: "Augury",
    titleRus: "Предсказание",
    level: "2",
    ritual: "TRUE",
    castingTime: "1 minute or Ritual",
    castingTimeRus: "1 минута или ритуал",
    rangeFt: "Self",
    componentV: "TRUE",
    componentS: "TRUE",
    componentM:
      "specially marked sticks, bones, cards, or other divinatory tokens worth 25+ GP",
    componentMRus:
      "особые палочки с отметинами, костяшки, карты, или другие гадальные принадлежности, стоящие 25+ зм",
    concentration: "FALSE",
    duration: "Instantaneous",
    durationRus: "Мгновенная",
    description:
      "You receive an omen from an otherworldly entity about the results of a course of action that you plan to take within the next 30 minutes. The DM chooses the omen from the Omens table.<br>\nThe spell doesn't account for circumstances, such as other spells, that might change the results.<br>\nIf you cast the spell more than once before finishing a Long Rest, there is a cumulative 25 percent chance for each casting after the first that you get no answer.",
    descriptionRus:
      "Вы получаете знамение от иномировой сущности о результатах определённого курса действий, которые вы планируете совершить в течение следующих 30 минут. Мастер выбирает знамение из таблицы Знамения.<br>\nЗаклинание не принимает в расчёт обстоятельства, такие как другие заклинания, способные изменить исход.<br>\nЕсли вы накладываете это заклинание более 1 раза до завершения продолжительного отдыха, то существует накопительный шанс 25% за каждое использование после первого, что вы не получите ответ.",
    onHigherLevel: "",
    onHigherLevelRus: "",
    school: "Divination",
    schoolRus: "Прорицание",
    classBarbarian: "FALSE",
    classBard: "FALSE",
    classCleric: "TRUE",
    classDruid: "TRUE",
    classFighter: "FALSE",
    classMonk: "FALSE",
    classPaladin: "FALSE",
    classRanger: "FALSE",
    classRogue: "FALSE",
    classSorcerer: "FALSE",
    classWarlock: "FALSE",
    classWizard: "TRUE",
    dopMaterial:
      "OMENS\nOmen Weal Good\nFor Results That Will Be ...\nWoe Bad\nWeal and woe Good and bad\nIndifference Neither good nor bad",
  },
  {
    "№": "21",
    title: "Aura of Life",
    titleRus: "Аура жизни",
    level: "4",
    ritual: "FALSE",
    castingTime: "Action",
    castingTimeRus: "Действие",
    rangeFt: "Self",
    componentV: "TRUE",
    componentS: "FALSE",
    componentM: "",
    componentMRus: "",
    concentration: "TRUE",
    duration: "Concentration , up to 10 minutes",
    durationRus: "Концентрация, до 10 минут",
    description:
      "An aura radiates from you in a 3O-foot Emanation for the duration. While in the aura, you and your allies have Resistance to Necrotic damage, and your Hit Point maximums can't be reduced. If an ally with O Hit Points starts its turn in the aura, that ally regains 1 Hit Point.",
    descriptionRus:
      "От вас исходит аура эмананацией на 30 футов во время длительности заклинания. Пока вы и ваши союзники находитесь в пределах ауры, то получаете сопротивление урону некротической энергией и максимальное количество ваших хитов не может быть уменьшено. Если союзник с 0 хитами начинает свой ход в пределах ауры, то он восстанавливает 1 хит.",
    onHigherLevel: "",
    onHigherLevelRus: "",
    school: "Abjuration",
    schoolRus: "",
    classBarbarian: "FALSE",
    classBard: "FALSE",
    classCleric: "TRUE",
    classDruid: "FALSE",
    classFighter: "FALSE",
    classMonk: "FALSE",
    classPaladin: "TRUE",
    classRanger: "FALSE",
    classRogue: "FALSE",
    classSorcerer: "FALSE",
    classWarlock: "FALSE",
    classWizard: "FALSE",
    dopMaterial: "",
  },
  {
    "№": "22",
    title: "Aura of Purity",
    titleRus: "Аура очищения",
    level: "4",
    ritual: "FALSE",
    castingTime: "Action",
    castingTimeRus: "Действие",
    rangeFt: "Self",
    componentV: "TRUE",
    componentS: "FALSE",
    componentM: "",
    componentMRus: "",
    concentration: "TRUE",
    duration: "Concentration , up to 10 minutes",
    durationRus: "Концентрация, до 10 минут",
    description:
      "An aura radiates from you in a 3O-foot Emanation for the duration. While in the aura, you and your allies have Resistance to Poison damage and Advantage on saving throws to avoid or end effects that include the Blinded, Charmed, Deafened, Frightened, Paralyzed, Poisoned, or Stunned condition.",
    descriptionRus:
      "От вас исходит аура эмананацией на 30 футов во время длительности заклинания. Пока вы и ваши союзники находитесь в пределах ауры, то получаете сопротивление к урону ядом и преимущество на спасброски для избегания или окончания эффектов, накладывающих следующие состояния ослеплённый, очарованный, оглохший, испуганный, парализованный, отравленный или ошеломлённый.",
    onHigherLevel: "",
    onHigherLevelRus: "",
    school: "Abjuration",
    schoolRus: "",
    classBarbarian: "FALSE",
    classBard: "FALSE",
    classCleric: "TRUE",
    classDruid: "FALSE",
    classFighter: "FALSE",
    classMonk: "FALSE",
    classPaladin: "TRUE",
    classRanger: "FALSE",
    classRogue: "FALSE",
    classSorcerer: "FALSE",
    classWarlock: "FALSE",
    classWizard: "FALSE",
    dopMaterial: "",
  },
  {
    "№": "23",
    title: "Aura of Vitality",
    titleRus: "(Аура жизненной силы)",
    level: "3",
    ritual: "FALSE",
    castingTime: "Action",
    castingTimeRus: "Действие",
    rangeFt: "Self",
    componentV: "TRUE",
    componentS: "FALSE",
    componentM: "",
    componentMRus: "",
    concentration: "TRUE",
    duration: "Concentration , up to 1 minute",
    durationRus: "Концентрация, до 1 минуты",
    description:
      "An aura radiates from you in a 3O-foot Emanation for the duration. When you create the aura and at the start of each of your turns while it persists, you can restore 2d6 Hit Points to one creature in it.",
    descriptionRus:
      "От вас исходит аура эмананацией на 30 футов во время длительности заклинания. Когда вы накладываете это заклинание и в начале каждого вашего хода, пока она действует, вы можете восстановить 2к6 хитов одному существу, находящемуся в её пределах.",
    onHigherLevel: "",
    onHigherLevelRus: "",
    school: "Abjuration",
    schoolRus: "",
    classBarbarian: "FALSE",
    classBard: "FALSE",
    classCleric: "TRUE",
    classDruid: "FALSE",
    classFighter: "FALSE",
    classMonk: "FALSE",
    classPaladin: "TRUE",
    classRanger: "FALSE",
    classRogue: "FALSE",
    classSorcerer: "FALSE",
    classWarlock: "FALSE",
    classWizard: "FALSE",
    dopMaterial: "",
  },
  {
    "№": "24",
    title: "Awaken",
    titleRus: "(Пробуждение)",
    level: "5",
    ritual: "FALSE",
    castingTime: "8 hours",
    castingTimeRus: "8 часов",
    rangeFt: "Touch",
    componentV: "TRUE",
    componentS: "TRUE",
    componentM: "an agate worth 1,000+ GP, which the spell consumes",
    componentMRus: "агат стоимостью 1000+ зм, расходуемый заклинанием",
    concentration: "FALSE",
    duration: "Instantaneous",
    durationRus: "Мгновенная",
    description:
      "You spend the casting time tracing magical pathways within a precious gemstone, and then touch the target. The target must be either a Beast or Plant creature with an Intelligence of 3 or less or a natural plant that isn't a creature. The target gains an Intelligence of 10 and the ability to speak one language you know. If the target is a natural plant, it becomes a Plant creature and gains the ability to move its limbs, roots, vines, creepers, and so forth, and it gains senses similar to a human's. The DM chooses statistics appropriate for the awakened Plant, such as the statistics for the <strong>Awakened Shrub</strong> or <strong>Awakened Tree</strong> in the Monster Manual.<br>\nThe awakened target has the Charmed condition for 30 days or until you or your allies deal damage to it. When that condition ends, the awakened creature chooses its attitude toward you.",
    descriptionRus:
      "Потратив время на прокладывание магических каналов в драгоценном камне, вы касаетесь им цели. Целью должна быть либо существо с типом зверь или растение и с Интеллектом 3 или ниже, либо обычное растение, которое не является существом. Интеллект цели становится равен 10 и она получает способность говорить на 1 известном вам языке. Если цель обычное растение не существо, то оно становится существом с типом растение, приобретает способность двигать своими конечностями, корнями, лианами, побегами и так далее, а также получает чувства, подобные человеческим. Мастер выбирает подходящий статблок для такого растения, такой как <strong>Пробужденный куст</strong> или <strong>Пробужденное дерево</strong> из Бестиария.<br>\nПробужденное существо получает состояние очарованный на 30 дней или до тех пор, пока вы или ваши союзники не нанесете ему урон. Когда это состояние заканчивается, то пробужденное существо само решает, каким будет его отношение к вам.",
    onHigherLevel: "",
    onHigherLevelRus: "",
    school: "Transmutation",
    schoolRus: "Преображения",
    classBarbarian: "FALSE",
    classBard: "TRUE",
    classCleric: "FALSE",
    classDruid: "TRUE",
    classFighter: "FALSE",
    classMonk: "FALSE",
    classPaladin: "FALSE",
    classRanger: "FALSE",
    classRogue: "FALSE",
    classSorcerer: "FALSE",
    classWarlock: "FALSE",
    classWizard: "FALSE",
    dopMaterial: "",
  },
  {
    "№": "25",
    title: "Bane",
    titleRus: "Порча",
    level: "1",
    ritual: "FALSE",
    castingTime: "Action",
    castingTimeRus: "Действие",
    rangeFt: "30",
    componentV: "TRUE",
    componentS: "TRUE",
    componentM: "a drop of blood",
    componentMRus: "капля крови",
    concentration: "TRUE",
    duration: "Concentration , up to 1 minute",
    durationRus: "Концентрация, до 1 минуты",
    description:
      "Up to th ree creatures of your choice that you can see within range must each make a Charisma saving throw. Whenever a target that fails this save makes an attack roll or a saving throw before the spell ends, the target must subtract ld4 from the attack roll or save.",
    descriptionRus:
      "До 3 существ в пределах дистанции, которых вы видите, должны совершить спасброски Харизмы. Пока заклинание активно, каждый раз, когда цель, провалившая этот спасбросок, совершает бросок атаки или спасбросок, она должна бросать к4 и вычитать выпавший результат из броска атаки или спасброска.",
    onHigherLevel:
      "You can target one additional creature for each spell slot level above 1.",
    onHigherLevelRus:
      "Вы можете сделать целью 1 дополнительное существо за каждый уровень ячейки выше 1.",
    school: "Enchantment",
    schoolRus: "Очарования",
    classBarbarian: "FALSE",
    classBard: "TRUE",
    classCleric: "TRUE",
    classDruid: "FALSE",
    classFighter: "FALSE",
    classMonk: "FALSE",
    classPaladin: "FALSE",
    classRanger: "FALSE",
    classRogue: "FALSE",
    classSorcerer: "FALSE",
    classWarlock: "TRUE",
    classWizard: "FALSE",
    dopMaterial: "",
  },
  {
    "№": "26",
    title: "Banishing Smite",
    titleRus: "Изгоняюший удар",
    level: "5",
    ritual: "FALSE",
    castingTime: "Bonus Action",
    castingTimeRus: "Бонусное Действие",
    rangeFt: "Self",
    componentV: "TRUE",
    componentS: "FALSE",
    componentM: "",
    componentMRus: "",
    concentration: "TRUE",
    duration: "Concentration , up to 1 minute",
    durationRus: "Концентрация, до 1 минуты",
    description:
      "(Bonus Action, which you take immediately after hitting a creature with a Melee weapon or an Unarmed Strike).<br>\nThe target hit by the attack roll takes an extra 5d10 Force damage from the attack. If the attack reduces the target to 50 Hit Points or fewer, the target must succeed on a Charisma saving throw or be transported to a harmless demiplane for the duration. While there, the target has the Incapacitated condition. When the spell ends, the target reappears in the space it left or in the nearest unoccupied space if that space is occupied.",
    descriptionRus:
      "(Бонусное действие, которое вы совершаете сразу после попадания по существу рукопашным оружием или безоружным ударом.)<br>\nЦель, поражённая этим броском атаки, получает от этой атаки дополнительно 5к10 урона силовым полем. Если после атаки у цели остаётся 50 хитов или меньше, то она должна совершить спасбросок Харизмы или быть перемещённой на безвредный демиплан на время длительности заклинания. Находясь там, цель находится в состоянии недееспособный. Когда заклинание заканчивается, цель возвращается на место, откуда исчезла, или в ближайшее свободное пространство, если исходное место занято.",
    onHigherLevel: "",
    onHigherLevelRus: "",
    school: "Conjuration",
    schoolRus: "",
    classBarbarian: "FALSE",
    classBard: "FALSE",
    classCleric: "FALSE",
    classDruid: "FALSE",
    classFighter: "FALSE",
    classMonk: "FALSE",
    classPaladin: "TRUE",
    classRanger: "FALSE",
    classRogue: "FALSE",
    classSorcerer: "FALSE",
    classWarlock: "FALSE",
    classWizard: "FALSE",
    dopMaterial: "",
  },
  {
    "№": "27",
    title: "Banishment",
    titleRus: "Изгнание",
    level: "4",
    ritual: "FALSE",
    castingTime: "Action",
    castingTimeRus: "Действие",
    rangeFt: "30",
    componentV: "TRUE",
    componentS: "TRUE",
    componentM: "a pentacle",
    componentMRus: "пентакль",
    concentration: "TRUE",
    duration: "Concentration , up to 1 minute",
    durationRus: "Концентрация, до 1 минуты",
    description:
      "One creature that you can see within range must succeed on a Charisma saving throw or be transported to a harmless demiplane for the duration. While t here, the target has the Incapacitated condition. When the spell ends, the target reappears in the space it left or in the nearest unoccupied space if that space is occupied.<br>\nIf the target is an Aberration, a Celestial, an Elemental, a Fey. or a Fiend, the target doesn't return if the spell lasts for 1 minute. The target is instead transported to a random location on a plane (DM's choice) associated with its creature type.",
    descriptionRus:
      "1 существо, которое вы видите в пределах дистанции, должно преуспеть в спасброске Харизмы или быть перенесено в безопасный демиплан на время длительности заклинания. Находясь там, цель получает состояние недееcпособный. Когда заклинание заканчивается, цель возвращается в то пространство, которое покинула, или в ближайшее незанятое пространство, если исходное пространство занято.<br>\nЕсли целью является существо с типом аберрация, небожитель, элементаль, фея или исчадие и заклинание длится 1 минуту, то цель не возвращается. Вместо этого цель переносится в случайное место на плане (на усмотрение Мастера), ассоциированном с её типом существа.",
    onHigherLevel:
      "You can target one additional creature for each spell slot level above 4.",
    onHigherLevelRus:
      "Вы можете выбрать 1 дополнительную цель за каждый уровень ячейки выше 4.",
    school: "Abjuration",
    schoolRus: "",
    classBarbarian: "FALSE",
    classBard: "FALSE",
    classCleric: "TRUE",
    classDruid: "FALSE",
    classFighter: "FALSE",
    classMonk: "FALSE",
    classPaladin: "TRUE",
    classRanger: "FALSE",
    classRogue: "FALSE",
    classSorcerer: "TRUE",
    classWarlock: "TRUE",
    classWizard: "TRUE",
    dopMaterial: "",
  },
  {
    "№": "28",
    title: "Barkskin",
    titleRus: "Дубовая кожа",
    level: "2",
    ritual: "FALSE",
    castingTime: "Bonus Action",
    castingTimeRus: "Бонусное Действие",
    rangeFt: "Touch",
    componentV: "TRUE",
    componentS: "TRUE",
    componentM: "a handful of bark",
    componentMRus: "пригоршня коры",
    concentration: "FALSE",
    duration: "1 hour",
    durationRus: "1 час",
    description:
      "You touch a willing creature. Until the spell ends, the target's skin assumes a bark-like appearance, and the target has an Armor Class of 17 if its AC is lower than that.",
    descriptionRus:
      "Вы касаетесь согласного существа. До окончания закнинания кожа цели становится грубой и похожей внешне на кору дуба, и цель имеет 17 КД, если её КД был ниже.",
    onHigherLevel: "",
    onHigherLevelRus: "",
    school: "Transmutation",
    schoolRus: "Преображения",
    classBarbarian: "FALSE",
    classBard: "FALSE",
    classCleric: "FALSE",
    classDruid: "TRUE",
    classFighter: "FALSE",
    classMonk: "FALSE",
    classPaladin: "FALSE",
    classRanger: "TRUE",
    classRogue: "FALSE",
    classSorcerer: "FALSE",
    classWarlock: "FALSE",
    classWizard: "FALSE",
    dopMaterial: "",
  },
  {
    "№": "29",
    title: "Beacon of Hope",
    titleRus: "Маяк надежды",
    level: "3",
    ritual: "FALSE",
    castingTime: "Action",
    castingTimeRus: "Действие",
    rangeFt: "30",
    componentV: "TRUE",
    componentS: "TRUE",
    componentM: "",
    componentMRus: "",
    concentration: "TRUE",
    duration: "Concentration , up to 1 minute",
    durationRus: "Концентрация, до 1 минуты",
    description:
      "Choose any number of creatures within range. For the duration, each target has Advantage on Wisdom saving throws and Death Saving Throws and regains the maximum number of Hit Points possible from any healing.",
    descriptionRus:
      "Выберите любое количество существ в пределах досягаемости. На время действия заклинания каждое выбранное существо получает преимущество на спасброски Мудрости и спасброски от смерти, а также восстанавливает максимально возможное количество хитов от любого лечения.",
    onHigherLevel: "",
    onHigherLevelRus: "",
    school: "Abjuration",
    schoolRus: "",
    classBarbarian: "FALSE",
    classBard: "FALSE",
    classCleric: "TRUE",
    classDruid: "FALSE",
    classFighter: "FALSE",
    classMonk: "FALSE",
    classPaladin: "FALSE",
    classRanger: "FALSE",
    classRogue: "FALSE",
    classSorcerer: "FALSE",
    classWarlock: "FALSE",
    classWizard: "FALSE",
    dopMaterial: "",
  },
  {
    "№": "30",
    title: "Beast Sense",
    titleRus: "Животные чувства",
    level: "2",
    ritual: "TRUE",
    castingTime: "Action or Ritual",
    castingTimeRus: "Действие или ритуал",
    rangeFt: "Touch",
    componentV: "FALSE",
    componentS: "TRUE",
    componentM: "",
    componentMRus: "",
    concentration: "TRUE",
    duration: "Concentration, up to 1 hour",
    durationRus: "Концентрация, до 1 часа",
    description:
      "You touch a willing Beast. For the duration, you can perceive through the Beast's senses as well as your own. When perceiving through the Beast's senses, you benefit from any special senses it has.",
    descriptionRus:
      "Вы касаетесь согласного зверя. На время длительности заклинания вы можете воспринимать мир через его чувства, а также через свои собственные. При восприятии через чувства зверя вы получаете эффекты от любых особых чувств, которыми он обладает.",
    onHigherLevel: "",
    onHigherLevelRus: "",
    school: "Divination",
    schoolRus: "Прорицание",
    classBarbarian: "FALSE",
    classBard: "FALSE",
    classCleric: "FALSE",
    classDruid: "TRUE",
    classFighter: "FALSE",
    classMonk: "FALSE",
    classPaladin: "FALSE",
    classRanger: "TRUE",
    classRogue: "FALSE",
    classSorcerer: "FALSE",
    classWarlock: "FALSE",
    classWizard: "FALSE",
    dopMaterial: "",
  },
  {
    "№": "31",
    title: "Befuddlement",
    titleRus: "Замешательство",
    level: "8",
    ritual: "FALSE",
    castingTime: "Action",
    castingTimeRus: "Действие",
    rangeFt: "150",
    componentV: "TRUE",
    componentS: "TRUE",
    componentM: "a key ring with no keys",
    componentMRus: "кольцо для ключей без ключей",
    concentration: "FALSE",
    duration: "Instantaneous",
    durationRus: "Мгновенная",
    description:
      "You blast the mind of a creature that you can see within range. The target makes an Intelligence saving throw. <br>\nOn a failed save, the target takes 10d12 Psychic damage and can't cast spells or take the Magic action. At the end of every 30 days, the target repeats the save, ending the effect on a success. The effect can also be ended by the Greater Restoration, Heal, or Wish spell.<br>\nOn a successful save, the target takes half as much damage only.",
    descriptionRus:
      "Вы поражаете разум существа, которое видите в пределах дистанции. Цель совершает спасбросок Интеллекта.<br>\nПри провале цель получает 10к12 урона психической энергией и не может накладывать заклинания или совершать действие магия. В конце каждого 30 дня цель повторяет спасбросок, завершив эффект при успехе. Эффект также может быть снят с помощью заклинаний Высшее восстановление, Исцеление или Желание.<br>\nПри успешном спасброске цель получает только половину урона.",
    onHigherLevel: "",
    onHigherLevelRus: "",
    school: "Enchantment",
    schoolRus: "Очарования",
    classBarbarian: "FALSE",
    classBard: "TRUE",
    classCleric: "FALSE",
    classDruid: "TRUE",
    classFighter: "FALSE",
    classMonk: "FALSE",
    classPaladin: "FALSE",
    classRanger: "FALSE",
    classRogue: "FALSE",
    classSorcerer: "FALSE",
    classWarlock: "TRUE",
    classWizard: "TRUE",
    dopMaterial: "",
  },
  {
    "№": "32",
    title: "Bestow Curse",
    titleRus: "Проклятие",
    level: "3",
    ritual: "FALSE",
    castingTime: "Action",
    castingTimeRus: "Действие",
    rangeFt: "Touch",
    componentV: "TRUE",
    componentS: "TRUE",
    componentM: "",
    componentMRus: "",
    concentration: "TRUE",
    duration: "Concentration , up to 1 minute",
    durationRus: "Концентрация, до 1 минуты",
    description:
      "You touch a creature, which must succeed on a Wisdom saving throw or become cursed for the duration. Until the curse ends, the target suffers one of the following effects of your choice:<br><br>\n• Choose one ability. The target has Disadvantage on ability checks and saving throws made with that ability.<br>\n• The target has Disadvantage on attack rolls against you.<br>\n• In combat, the target must succeed on a Wisdom saving throw at the start of each of its turns or be forced to take the Dodge action on that turn.<br>\n• If you deal damage to the target with an attack roll or a spell, the target takes an extra 1d8 Necrotic damage.",
    descriptionRus:
      "Вы касаетесь существа, и оно должно преуспеть в спасброске Мудрости, иначе станет проклятым на период действия заклинания. Пока проклятье действует, цель страдает от одного из следующих эффектов на ваш выбор:<br><br>\n• Выберите одну характеристику. Цель совершает проверки и спасброски этой характеристики с помехой. <br>\n• Цель совершает с помехой броски атаки по вам.<br>\n• В бою цель должна в начале каждого своего хода преуспеть в спасброске Мудрости, иначе она должна потратить действие на уклонение в этот ход.<br>\n• Если вы нанесли урон цели, используя атаку или заклинание, то она получает дополнительно 1к8 урона некротической энергией.",
    onHigherLevel:
      "If you cast this spell using a level 4 spell slot, you can maintain Concentration on it for up to 10 minutes. If you use a level S+ spell slot, the spell doesn't require Concentration, and the duration becomes 8 hours (level 5-6 slot) or 24 hours (level 7-8 slot). If you use a level 9 spell slot, the spell lasts until dispelled.",
    onHigherLevelRus:
      "Если вы накладываете это заклинание, используя ячейку заклинаний 4 уровня, вы можете поддерживать концентрацию на нем до 10 минут. Если вы используете ячейку 5 уровня и выше, то заклинание не требует концентрации, а его продолжительность становится 8 часов (ячейки 5-6 уровня) или 24 часа (ячейки 7-8 уровня). Если вы используете ячейку 9 уровня, то заклинание длится до развеивания.",
    school: "Necrnmancy",
    schoolRus: "Некромантия",
    classBarbarian: "FALSE",
    classBard: "TRUE",
    classCleric: "TRUE",
    classDruid: "FALSE",
    classFighter: "FALSE",
    classMonk: "FALSE",
    classPaladin: "FALSE",
    classRanger: "FALSE",
    classRogue: "FALSE",
    classSorcerer: "FALSE",
    classWarlock: "FALSE",
    classWizard: "TRUE",
    dopMaterial: "",
  },
  {
    "№": "33",
    title: "Bigby's Hand",
    titleRus: "Рука Бигби",
    level: "5",
    ritual: "FALSE",
    castingTime: "Action",
    castingTimeRus: "Действие",
    rangeFt: "120",
    componentV: "TRUE",
    componentS: "TRUE",
    componentM: "an eggshell and a glove",
    componentMRus: "яичная скорлупа и перчатка",
    concentration: "TRUE",
    duration: "Concentration , up to 1 minute",
    durationRus: "Концентрация, до 1 минуты",
    description:
      "You create a Large hand of shimmering magical energy in an unoccupied space that you can see within range. The hand lasts for the druration, and it moves at your command, mimicking the movements of your own hand.<br>\nThe hand is an object t hat has AC 20 and Hit Points equal to your Hit Point maximum. If it drops 0 too Hit Points, the spell ends. The hand doesn't occupy its space.<br>\nWhen you cast the spell and as a Bonus Action on your later turns, you can move the hand up to 60 feet and then cause one of the following effects:<br>\n<strong>Clenched Fist.<strong/> The hand strikes a target within 5 feet of it. Make a melee spell attack. On a hit, the target takes 5d8 Force damage.<br>\n<strong>Forceful Hand.<strong/> The hand attempts to push a Huge or smaller creature within 5 feet of it. The target must succeed on a Strength saving throw, or the hand pushes the target up to 5 feet plus a number of feet equal to five times your spellcasting ability modifier. The hand moves with the target, remaining within 5 feet of it.<br>\n<strong>Grasping Hand.<strong/> The hand attempts to grapple a Huge or smaller creature within 5 feet of it. The target must succeed on a Dexterity saving throw, or the target has the Grappled condition, with an escape DC equal to your spell save DC. While the hand grapples the target, you can take a Bonus Action to cause the hand to crush it, dealing Bludgeoning damage to the target equal to 4d6 plus your spellcasting ability modifier.<br>\n<strong>Interposing Hand.<strong/> The hand grants you Half Cover against attacks and other effects that originate from its space or that pass through it. In addition, its space counts as Difficult Terrain for your enemies.",
    descriptionRus:
      "Вы создаёте руку большого размера из мерцающей магической энергии в свободном пространстве, которое вы видите в пределах дистанции. Рука существует на протяжении длительности заклинания и двигается по вашему приказу, имитируя движения вашей собственной руки.<br>\nРука — это объект с КД 20 и Хитами, равными вашему максимальному количеству Хитов. Если хиты руки опускается до 0, заклинание заканчивается. Рука не занимает пространство, в котором находится.<br>\nКогда вы накладываете заклинание и бонусным действием на ваших последующих ходах, вы можете переместить руку на расстояние до 60 футов и вызвать одно из следующих действий:<br>\n<strong>Сжатый кулак.<strong/> Рука наносит удар по цели в пределах 5 футов от неё. Совершите рукопашную атаку заклинанием. При попадании цель получает 5к8 урона силовым полем.<br>\n<strong>Могучая длань.<strong/> Рука пытается толкнуть существо огромного или меньшего размера в пределах 5 футов от неё. Цель должна преуспеть в спасброске Силы, иначе рука толкает её на 5 футов плюс количество футов, равное модификатору вашей заклинательной характеристики, умноженному на 5. Рука движется вместе с целью, оставаясь в пределах 5 футов от неё.<br>\n<strong>Сжимающая длань.<strong/> Рука пытается схватить существо огромного или меньшего размера в пределах 5 футов от неё. Цель должна преуспеть в спасброске Ловкости, иначе цель получает состояние схваченный, со Сл. освобождения, равной Сл. спасброска ваших заклинаний. Пока рука держит цель, вы можете бонусным действием заставить руку сжать её, нанося дробящий урон цели в размере 4к6 плюс ваш модификатор заклинательной характеристики.<br>\n<strong>Преграждающая длань.<strong/> Рука предоставляет вам укрытие на половину от атак и других эффектов, которые исходят из её пространства или проходят через него. Кроме того, её пространство считается труднопроходимой местностью для ваших врагов.",
    onHigherLevel:
      "The damage of the Clenched Fist increases by 2d8 and the damage of the Grasping Hand increases by 2d6 for each spell slot level above 5.",
    onHigherLevelRus:
      "Урон от Сжатого кулака увеличивается на 2к8 и урон от Сжимающей длани увеличивается на 2к6 за каждый уровень ячейки заклинания выше 5го.",
    school: "Evocation",
    schoolRus: "Созидания",
    classBarbarian: "FALSE",
    classBard: "FALSE",
    classCleric: "FALSE",
    classDruid: "FALSE",
    classFighter: "FALSE",
    classMonk: "FALSE",
    classPaladin: "FALSE",
    classRanger: "FALSE",
    classRogue: "FALSE",
    classSorcerer: "TRUE",
    classWarlock: "FALSE",
    classWizard: "TRUE",
    dopMaterial: "",
  },
  {
    "№": "34",
    title: "Blade Barrier",
    titleRus: "Стена Клинков",
    level: "6",
    ritual: "FALSE",
    castingTime: "Action",
    castingTimeRus: "Действие",
    rangeFt: "90",
    componentV: "TRUE",
    componentS: "TRUE",
    componentM: "",
    componentMRus: "",
    concentration: "TRUE",
    duration: "Concentration , up to 10 minute",
    durationRus: "Концентрация, до 10 минуты",
    description:
      "You create a wall of whirling blades made of magical energy. The wall appears within range and lasts for the duration. You make a straight wall up to 100 feet long, 20 feet high, and 5 feet thick, or a ringed wall up to 60 feet in diameter, 20 feet high, and 5 feet thick. The wall provides Three-Quarters Cover, and its space is Difficult Terrain.<br>\nAny creature in the wall's space makes a Dexterity saving throw, taking 6d10 Force damage on a failed save or half as much damage on a successful one. A creature also makes that save if it enters the wall's space or end it turn there. A creature makes that save only once per turn.",
    descriptionRus:
      "Вы создаёте стену из крутящихся бритвенноострых клинков из магической энергии. Стена появляется в пределах дистанции и существует на протяжении длительности заклинания. Вы можете создать прямую стену длиной 100 футов, высотой 20 футов и толщиной 5 футов, или закольцованную стену диаметром 60 футов, высотой 20 футов и толщиной 5 футов.<br>\nСтена предоставляет существам, находящимся за ней, укрытие на три четверти, и её пространство является труднопроходимой местностью. Любое существо в пространстве стены совершает спасбросок Ловкости, получая 6к10 урона силовым полем при провале или половину этого урона при успехе. Существо также совершает этот спасбросок, если входит в пространство стены или заканчивает в нём свой ход. Однако существо совершает этот спасбросок только 1 раз за ход.",
    onHigherLevel: "",
    onHigherLevelRus: "",
    school: "Evocation",
    schoolRus: "Созидания",
    classBarbarian: "FALSE",
    classBard: "FALSE",
    classCleric: "TRUE",
    classDruid: "FALSE",
    classFighter: "FALSE",
    classMonk: "FALSE",
    classPaladin: "FALSE",
    classRanger: "FALSE",
    classRogue: "FALSE",
    classSorcerer: "FALSE",
    classWarlock: "FALSE",
    classWizard: "FALSE",
    dopMaterial: "",
  },
  {
    "№": "35",
    title: "Blade Ward",
    titleRus: "Защита от Оружия",
    level: "0",
    ritual: "FALSE",
    castingTime: "Action",
    castingTimeRus: "Действие",
    rangeFt: "Self",
    componentV: "TRUE",
    componentS: "TRUE",
    componentM: "",
    componentMRus: "",
    concentration: "TRUE",
    duration: "Concentration , up to 1 minute",
    durationRus: "Концентрация, до 1 минуты",
    description:
      "Whenever a creature makes an attack roll against you before the spell ends, the attacker subtracts 1d4 from the attack roll.",
    descriptionRus:
      "Концентрация, до 1 минуты Каждый раз, когда существо совершает атаку по вам до окончания длительности заклинания, то атакующий вычитает 1к4 из броска атаки.",
    onHigherLevel: "",
    onHigherLevelRus: "",
    school: "Abjuration",
    schoolRus: "",
    classBarbarian: "FALSE",
    classBard: "TRUE",
    classCleric: "FALSE",
    classDruid: "FALSE",
    classFighter: "FALSE",
    classMonk: "FALSE",
    classPaladin: "FALSE",
    classRanger: "FALSE",
    classRogue: "FALSE",
    classSorcerer: "TRUE",
    classWarlock: "TRUE",
    classWizard: "TRUE",
    dopMaterial: "",
  },
  {
    "№": "36",
    title: "Bless",
    titleRus: "Благословение",
    level: "1",
    ritual: "FALSE",
    castingTime: "Action",
    castingTimeRus: "Действие",
    rangeFt: "30",
    componentV: "TRUE",
    componentS: "TRUE",
    componentM: "a Holy Symbol worth 5+ GP",
    componentMRus: "Священный символ стоимостью 5+ зм",
    concentration: "TRUE",
    duration: "Concentration , up to 1 minute",
    durationRus: "Концентрация, до 1 минуты",
    description:
      "You bless up to three creatures within range. Whenever a target makes an attack roll or a saving throw before the spell ends, the target adds ld4 to the attack roll or save.",
    descriptionRus:
      "Вы благословляете до 3 существ в пределах дистанции. Каждый раз, когда цель совершает бросок атаки или спасбросок до окончания длительности заклинания, она может добавить 1к4 к броску атаки или спасброску.",
    onHigherLevel:
      "You can target one additional creature for each spell slot level above 1.",
    onHigherLevelRus:
      "Вы можете сделать целью 1 дополнительное существо за каждый уровень ячейки выше 1.",
    school: "Enchantment",
    schoolRus: "Очарования",
    classBarbarian: "FALSE",
    classBard: "FALSE",
    classCleric: "TRUE",
    classDruid: "FALSE",
    classFighter: "FALSE",
    classMonk: "FALSE",
    classPaladin: "TRUE",
    classRanger: "FALSE",
    classRogue: "FALSE",
    classSorcerer: "FALSE",
    classWarlock: "FALSE",
    classWizard: "FALSE",
    dopMaterial: "",
  },
  {
    "№": "37",
    title: "Blight",
    titleRus: "Усыхание",
    level: "4",
    ritual: "FALSE",
    castingTime: "Action",
    castingTimeRus: "Действие",
    rangeFt: "30",
    componentV: "TRUE",
    componentS: "TRUE",
    componentM: "",
    componentMRus: "",
    concentration: "FALSE",
    duration: "Instantaneous",
    durationRus: "Мгновенная",
    description:
      "A creature that you can see within range makes a Constitution saving throw, taking 8d8 Necrotic damage on a failed save or half as much damage on a successful one. A Plant creature automatically fails the save.<br>\nAlternatively, target a nonmagical plant that isn't a creature, such as a tree or shrub. It doesn't make a save; it simply withers and dies.",
    descriptionRus:
      "Существо, которое вы видите в пределах дистанции заклинания, совершает спасбросок Телосложения, получая 8к8 урона некротической энергией в случае провала или половину этого урона в случае успеха. Существа с типом растение автоматически проваливают этот спасбросок.<br>\nЕсли цель — немагическое растение, не являющееся существом (например, дерево или куст), то оно не совершает спасбросок; а просто засыхает и умирает.",
    onHigherLevel:
      "The damage increases by ld8 for each spell slot level above 4.",
    onHigherLevelRus:
      "Урон увеличивается на 1к8 за каждый уровень ячейки выше 4.",
    school: "Necrnmancy",
    schoolRus: "Некромантия",
    classBarbarian: "",
    classBard: "",
    classCleric: "",
    classDruid: "TRUE",
    classFighter: "",
    classMonk: "",
    classPaladin: "",
    classRanger: "",
    classRogue: "",
    classSorcerer: "TRUE",
    classWarlock: "TRUE",
    classWizard: "TRUE",
    dopMaterial: "",
  },
  {
    "№": "38",
    title: "Blinding Smite",
    titleRus: "Ослепляющая кара",
    level: "3",
    ritual: "FALSE",
    castingTime: "Bonus Action",
    castingTimeRus: "Бонусное Действие",
    rangeFt: "Self",
    componentV: "TRUE",
    componentS: "FALSE",
    componentM: "",
    componentMRus: "",
    concentration: "FALSE",
    duration: "1 minute",
    durationRus: "1 минута",
    description:
      "(Bonus Action, which you take immediately after hitting a creature with a Melee weapon or an Unarmed Strike).<br>\nThe target hit by the strike takes an extra 3d8 Radiant damage from the attack, and the target has the Blinded condition until the spell ends. At the end of each of its turns, the Blinded target makes a Constitution saving throw, ending the spell on itself on a success.",
    descriptionRus:
      "(Бонусное действие, которое вы совершаете сразу после попадания по существу рукопашным оружием или безоружным ударом.)<br>\nЦель, поражённая этой атакой, получает дополнительно 3к8 урона излучением от этой атаки и цель получает состояние ослеплённый до конца длительности заклинания. В конце своего хода ослеплённая цель делает спасбросок Телосложения, оканчивая эффект заклинания на себе при успехе.",
    onHigherLevel:
      "The extra damage increases by ld8 for each spell slot level above 3.",
    onHigherLevelRus:
      "Дополнительный урон увеличивается на 1к8 за за каждый уровень ячейки выше 3.",
    school: "Evocation",
    schoolRus: "Созидания",
    classBarbarian: "",
    classBard: "",
    classCleric: "",
    classDruid: "",
    classFighter: "",
    classMonk: "",
    classPaladin: "TRUE",
    classRanger: "",
    classRogue: "",
    classSorcerer: "",
    classWarlock: "",
    classWizard: "",
    dopMaterial: "",
  },
  {
    "№": "39",
    title: "Blindness / Deafness",
    titleRus: "Глухота / Слепота",
    level: "2",
    ritual: "FALSE",
    castingTime: "Action",
    castingTimeRus: "Действие",
    rangeFt: "120",
    componentV: "TRUE",
    componentS: "FALSE",
    componentM: "",
    componentMRus: "",
    concentration: "FALSE",
    duration: "1 minute",
    durationRus: "1 минута",
    description:
      "One creature that you can see within range must succeed on a Constitution saving throw, or it has the Blinded or Deafened condition (your choice) for the duration. At the end of each of its turns, the target repeats the save, ending the spell on itself on a success.",
    descriptionRus:
      "1 существо, которое вы видите в пределах дистанции, должно преуспеть в спасброске Телосложения, иначе получит состояние ослеплённый или оглохший (на ваш выбор) на время длительности заклинания. В конце каждого своего хода цель повторяет спасбросок, заканчивая заклинание на себе в случае успеха.",
    onHigherLevel:
      "You can target one additional creature for each spell slot level above 2.",
    onHigherLevelRus:
      "Вы можете сделать целью 1 дополнительное существо за каждый уровень ячейки выше 2.",
    school: "Transmutation",
    schoolRus: "Преображения",
    classBarbarian: "",
    classBard: "TRUE",
    classCleric: "TRUE",
    classDruid: "",
    classFighter: "",
    classMonk: "",
    classPaladin: "",
    classRanger: "",
    classRogue: "",
    classSorcerer: "TRUE",
    classWarlock: "",
    classWizard: "TRUE",
    dopMaterial: "",
  },
  {
    "№": "40",
    title: "Blink",
    titleRus: "Мерцание",
    level: "3",
    ritual: "FALSE",
    castingTime: "Action",
    castingTimeRus: "Действие",
    rangeFt: "Self",
    componentV: "TRUE",
    componentS: "TRUE",
    componentM: "",
    componentMRus: "",
    concentration: "FALSE",
    duration: "1 minute",
    durationRus: "1 минута",
    description:
      "Roll ld6 at the end of each of your turns for the duration. On a roll of 4-6, you vanish from your current plane of existence and appear in the Ethereal Plane (the spell ends instantly if you are already on that plane). While on the Ethereal Plane, you can perceive the plane you left, which is cast in shades of gray, but you can't see anything there more than 60 feet away. You can affect and be affected only by other creatures on the Ethereal Plane, and creatures on the other plane can't perceive you unless they have a special ability that lets them perceive things on the Ethereal Plane.<br>\nYou return to the other plane at the start of your next turn and when the spell ends if you are on the Ethereal Plane. You return to an unoccupied space of your choice that you can see within 10 feet of the space you left. If no unoccupied space is available within that range, you appear in the nearest unoccupied space.",
    descriptionRus:
      "Бросайте 1к6 в конце каждого из ваших ходов в течение длительности. При результате броска 4-6 вы исчезаете с вашего текущего плана существования и появляетесь на Эфирном плане (заклинание мгновенно заканчивается, если вы уже находитесь на этом плане). Находясь на Эфирном плане, вы можете воспринимать план, который вы покинули, в оттенках серого и вы можете видеть там только на расстоянии не более 60 футов. Вы можете взаимодействовать и быть затронутыми только другими существами на Эфирном плане и существа на другом плане не могут воспринимать вас, если у них нет специальной способности, позволяющей видеть существ на Эфирном плане.<br>\nВы возвращаетесь на другой план в начале вашего следующего хода и когда заклинание заканчивается, если вы находитесь на Эфирном плане. Вы возвращаетесь в незанятое пространство по вашему выбору, которое вы видите в пределах 10 футов от того места, где вы покинули план. Если в этом диапазоне нет свободного пространства, то вы появляетесь в ближайшем незанятом пространстве.",
    onHigherLevel: "",
    onHigherLevelRus: "",
    school: "Transmutation",
    schoolRus: "Преображения",
    classBarbarian: "",
    classBard: "",
    classCleric: "",
    classDruid: "",
    classFighter: "",
    classMonk: "",
    classPaladin: "",
    classRanger: "",
    classRogue: "",
    classSorcerer: "TRUE",
    classWarlock: "",
    classWizard: "TRUE",
    dopMaterial: "",
  },
  {
    "№": "41",
    title: "Blur",
    titleRus: "Размытый образ",
    level: "2",
    ritual: "FALSE",
    castingTime: "Action",
    castingTimeRus: "Действие",
    rangeFt: "Self",
    componentV: "TRUE",
    componentS: "FALSE",
    componentM: "",
    componentMRus: "",
    concentration: "TRUE",
    duration: "Concentration , up to 1 minute",
    durationRus: "Концентрация, до 1 минуты",
    description:
      "Your body becomes blurred. For the duration, any creature has Disadvantage on attack rolls against you. An attacker is immune to this effect if it perceives you with Blindsight or Truesight.",
    descriptionRus:
      "Ваше тело становится размытым. На время длительности любое существо получает помеху на броски атаки против вас. Атакующий получает иммунитет к этому эффекту, если видит вас с помощью слепого или истинного зрения.",
    onHigherLevel: "",
    onHigherLevelRus: "",
    school: "Illusion",
    schoolRus: "",
    classBarbarian: "",
    classBard: "",
    classCleric: "",
    classDruid: "",
    classFighter: "",
    classMonk: "",
    classPaladin: "",
    classRanger: "",
    classRogue: "",
    classSorcerer: "TRUE",
    classWarlock: "",
    classWizard: "TRUE",
    dopMaterial: "",
  },
  {
    "№": "42",
    title: "Burning Hands",
    titleRus: "Огненные Ладони",
    level: "1",
    ritual: "FALSE",
    castingTime: "Action",
    castingTimeRus: "Действие",
    rangeFt: "Self",
    componentV: "TRUE",
    componentS: "FALSE",
    componentM: "",
    componentMRus: "",
    concentration: "FALSE",
    duration: "Instantaneous",
    durationRus: "Мгновенная",
    description:
      "A thin sheet of flames shoots forth from you. Each creature in a 15-foot Cone makes a Dexterity saving throw, taking 3d6 Fire damage on a failed save or half as much damage on a successful one.<br>\nFlammable objects in the Cone that aren't being worn or carried start burning.",
    descriptionRus:
      "Тонкий пласт пламени вырывается от вас. Каждое существо в пределах 15-футового конуса должно совершить спасбросок Ловкости, получая 3к6 урона огнём в случае провала или половину этого урона в случае успеха.<br>\nПламя поджигает все горючие предметы, никем не несомые и не носимые.",
    onHigherLevel:
      "The damage increases by ld6 for each spell slot level above 1.",
    onHigherLevelRus:
      "Урон увеличивается на 1к6 за каждый уровень ячейки выше 1.",
    school: "Evocation",
    schoolRus: "Созидания",
    classBarbarian: "",
    classBard: "",
    classCleric: "",
    classDruid: "",
    classFighter: "",
    classMonk: "",
    classPaladin: "",
    classRanger: "",
    classRogue: "",
    classSorcerer: "TRUE",
    classWarlock: "",
    classWizard: "TRUE",
    dopMaterial: "",
  },
  {
    "№": "43",
    title: "Call Lightning",
    titleRus: "Призыв Молний",
    level: "3",
    ritual: "FALSE",
    castingTime: "Action",
    castingTimeRus: "Действие",
    rangeFt: "120",
    componentV: "TRUE",
    componentS: "TRUE",
    componentM: "",
    componentMRus: "",
    concentration: "TRUE",
    duration: "Concentration , up to 10 minute",
    durationRus: "Концентрация, до 10 минуты",
    description:
      "A storm cloud appears at a point within range that you can see above yourself. It takes the shape of a Cylinder that is 10 feet tall with a 60-foot radius.<br>\nWhen you cast the spell, choose a point you can see under the cloud. A lightning bolt shoots from the cloud to that point. Each creature within 5 feet of that point makes a Dexterity saving throw, taking 3d10 Lightning damage on a failed save or half as much damage on a successful one.<br>\nUntil the spell ends, you can take a Magic action to call down lightning in that way again, targeting the same point or a different one.<br>\nIf you're outdoors in a storm when you cast this spell, the spell gives you control over that storm instead of creating a new one. Under such conditions, the spell's damage increases by 1d10.",
    descriptionRus:
      "Над вами в пределах видимой дистанции появляется туча в форме цилиндра 10 футов в высоту и с радиусом 60 футов.<br>\nКогда вы накладываете заклинание, выберите точку, которую можете видеть под этой тучей. Молния ударяет из облака в эту точку. Каждое существо в пределах 5 футов от этой точки совершает спасбросок Ловкости, получая 3к10 урона электричеством при провале или половину этого урона при успешном спасброске.<br>\nДо окончания заклинания вы можете совершить действие магия, чтобы снова призвать молнию таким же образом, нацеливаясь на ту же точку или другую.<br>\nЕсли вы находитесь на открытом воздухе во время бури, когда накладываете это заклинание, заклинание даёт вам контроль над этой бурей вместо создания новой. В таких условиях урон заклинания увеличивается на 1к10.",
    onHigherLevel:
      "The damage increases by 1d10 for each spell slot level above 3.",
    onHigherLevelRus:
      "Урон увеличивается на 1к10 за каждый уровень ячейки выше 3.",
    school: "Conjuration",
    schoolRus: "",
    classBarbarian: "",
    classBard: "",
    classCleric: "",
    classDruid: "TRUE",
    classFighter: "",
    classMonk: "",
    classPaladin: "",
    classRanger: "",
    classRogue: "",
    classSorcerer: "",
    classWarlock: "",
    classWizard: "",
    dopMaterial: "",
  },
];

const DndDataUploader = () => {
  // Функция для загрузки данных в Firebase
  const uploadData = async () => {
    const spellsCollection = collection(db, "spells");
    try {
      for (const spell of spells) {
        await addDoc(spellsCollection, spell);
        console.log(`Заклинание "${spell.title}" добавлено в базу данных!`);
      }
    } catch (error) {
      console.error("Ошибка при добавлении данных: ", error);
    }
  };

  return (
    <div>
      <p>Загрузить данные о заклинаниях</p>
      <button onClick={uploadData}>Загрузить заклинания в Firestore</button>
    </div>
  );
};

export default DndDataUploader;
