// src/components/DndDataUploader.js
import React from "react";
import { db } from "../../firebase/firebaseConfig"; // Путь к вашему файлу с конфигурацией Firebase
import { collection, addDoc } from "firebase/firestore";

// Массив заклинаний (данные для загрузки)
const spells = [
  {
    "№": "1",
    "title": "Acid Splash",
    "titleRus": "Кислотный Всплеск",
    "level": "0",
    "ritual": "FALSE",
    "castingTime": "Action",
    "castingTimeRus": "Действие",
    "rangeFt": "60",
    "componentV": "TRUE",
    "componentS": "TRUE",
    "componentM": "",
    "componentMRus": "",
    "concentration": "FALSE",
    "duration": "FALSE",
    "durationRus": "Мгновенно",
    "description": "You create an acid bubble at a point within range, where it explodes in a 5-foot-radius Sphere. Each creature in that Sphere must succeed on a Dexterity saving throw or take 1d6 Acid damage.",
    "descriptionRus": "Вы бросаете кислотный шарик в точку в пределах дальности, где он взрывается сферой с радиусом 5 футов. Каждое существо в этой сфере должно преуспеть в спаброске Ловкости или получить 1к6 урона кислотой.",
    "onHigherLevel": "The damage increases by 1d6 when you reach levels 5 (2d6), 11 (3d6), and 17 (4d6).",
    "onHigherLevelRus": "Урон увеличивается на 1к6, когда вы достигаете 5 уровня (2к6), 11 уровня (3к6) и 17 уровня (4к6).",
    "school": "Evocation",
    "schoolRus": "Созидания",
    "classBarbarian": "FALSE",
    "classBard": "FALSE",
    "classCleric": "FALSE",
    "classDruid": "FALSE",
    "classFighter": "FALSE",
    "classMonk": "FALSE",
    "classPaladin": "FALSE",
    "classRanger": "FALSE",
    "classRogue": "FALSE",
    "classSorcerer": "TRUE",
    "classWarlock": "FALSE",
    "classWizard": "TRUE"
},
{
    "№": "2",
    "title": "Aid",
    "titleRus": "(Подмога)",
    "level": "2",
    "ritual": "FALSE",
    "castingTime": "Action",
    "castingTimeRus": "Действие",
    "rangeFt": "30",
    "componentV": "TRUE",
    "componentS": "TRUE",
    "componentM": "a strip of white cloth",
    "componentMRus": "полоска белой ткани",
    "concentration": "FALSE",
    "duration": "8 hours",
    "durationRus": "8 часов",
    "description": "Choose up to three creatures within range. Each target's Hit Point maximum and current Hit Points increase by 5 for the duration.",
    "descriptionRus": "Выберите до 3 существ в пределах дистанции. На время длительности максимум хитов и текущие хиты всех целей увеличиваются на 5.",
    "onHigherLevel": "Each target's Hit Points increase by 5 for each spell slot level above 2",
    "onHigherLevelRus": "Хиты целей увеличиваются ещё на 5 за каждый уровень ячейки выше 2.",
    "school": "Abjuration",
    "schoolRus": "",
    "classBarbarian": "FALSE",
    "classBard": "TRUE",
    "classCleric": "TRUE",
    "classDruid": "TRUE",
    "classFighter": "FALSE",
    "classMonk": "FALSE",
    "classPaladin": "TRUE",
    "classRanger": "TRUE",
    "classRogue": "FALSE",
    "classSorcerer": "FALSE",
    "classWarlock": "FALSE",
    "classWizard": "FALSE"
},
{
    "№": "3",
    "title": "Alarm",
    "titleRus": "Тревога",
    "level": "1",
    "ritual": "TRUE",
    "castingTime": "1 minute or Ritual",
    "castingTimeRus": "1 минута или ритуал",
    "rangeFt": "30",
    "componentV": "TRUE",
    "componentS": "TRUE",
    "componentM": "a bell and silver wire",
    "componentMRus": "колокольчик и серебряная проволочка",
    "concentration": "FALSE",
    "duration": "8 hours",
    "durationRus": "8 часов",
    "description": "You set an alarm against intrusion. Choose a door, a window, or an area within range that is no larger than a 20-foot Cube. Until the spell ends, an alarm alerts you whenever a creature touches or enters the warded area. When you cast the spell, you can designate creatures that won't set off the alarm. You also choose whether the alarm is audible or mental:\nAudible Alarm. The alarm produces the sound of a handbell for 10 seconds within 60 feet of the warded area.\nMental Alarm. You are alerted by a mental ping if you are within 1 mile of the warded area. This ping awakens you if you're asleep.",
    "descriptionRus": "Вы устанавливаете сигнализацию на случай вторжения. Выберите дверь, окно или область в пределах дистанции не больше куба с длиной ребра 20 футов. До окончания действия заклинания тревога уведомляет вас каждый раз, когда существо входит или касается охраняемой области. При накладывании заклинания вы можете указать существ, которые не будут вызывать срабатывание тревоги. Вы также выбираете, будет тревога мысленной или звуковой.\nЗвуковая. Тревога издаёт звук колокольчика в течение 10 секунд в радиусе 60 футов от охраняемой области.\nМысленная. Вы получаете мысленный сигнал, если находитесь в радиусе 1 мили от охраняемой области. Этот сигнал будит вас, если вы спите.",
    "onHigherLevel": "",
    "onHigherLevelRus": "",
    "school": "Abjuration",
    "schoolRus": "",
    "classBarbarian": "FALSE",
    "classBard": "FALSE",
    "classCleric": "FALSE",
    "classDruid": "FALSE",
    "classFighter": "FALSE",
    "classMonk": "FALSE",
    "classPaladin": "FALSE",
    "classRanger": "TRUE",
    "classRogue": "FALSE",
    "classSorcerer": "FALSE",
    "classWarlock": "FALSE",
    "classWizard": "TRUE"
},
{
    "№": "4",
    "title": "Alter Self",
    "titleRus": "Смена Обличья",
    "level": "2",
    "ritual": "FALSE",
    "castingTime": "Action",
    "castingTimeRus": "Действие",
    "rangeFt": "Self",
    "componentV": "TRUE",
    "componentS": "TRUE",
    "componentM": "",
    "componentMRus": "",
    "concentration": "TRUE",
    "duration": "Concentration, up to 1 hour",
    "durationRus": "Концентрация, до 1 часа",
    "description": "You alter your physical form. Choose one of the following options. Its effects last for the duration, during which you can take a Magic action to replace the option you chose with a different one.\nAquatic Adaptation. You sprout gills and grow webs between your fingers. You can breathe underwater and gain a Swim Speed equal to your Speed.\nChange Appearance. You alter your appearance. You decide what you look like, including your height, weight, facial features, sound of your voice, hair length, coloration, and other distinguishing characteristics. You can make yourself appear as a member of another species, though none of your statistics change. You can't appear as a creature of a different size, and your basic shape stays the same; if you're bipedal, you can't use this spell to become quadrupedal, for instance. For the duration, you can take a Magic action to change your appearance in this way again.\nNatural Weapons. You grow claws (Slashing), fangs (Piercing), horns (Piercing), or hooves (Bludgeoning). When you use your Unarmed Strike to deal damage with that new growth, it deals ld6 damage of the type in parentheses instead of dealing the normal damage for your Unarmed Strike, and you use your spellcasting ability modifier for the attack and damage rolls rather than using Strength.",
    "descriptionRus": "Вы принимаете другой облик. При накладывании выберите один из представленных ниже вариантов, эффект от которого будет длиться всю длительность заклинания. Пока заклинание активно, вы можете использовать действие магия, чтобы заменить выбранный вами эффект другим.\nАдаптация к воде. Вы приспосабливаете своё тело к существованию в воде, отращивая жабры и перепонки между пальцами. Вы можете дышать под водой и получаете скорость плавания, равную вашей скорости.\nИзменение внешности. Вы изменяете свою внешность. Вы решаете, как будете выглядеть, включая рост, вес, черты лица, звук голоса, длину волос, цвет и другие отличительные характеристики. Вы можете стать похожим на представителя другого вида, но ваши показатели не изменяются. Вы не можете стать существом другого размера, и ваша основная форма остаётся той же; например, если вы двуногий, вы не можете с помощью этого заклинания стать четвероногим. В течение действия заклинания вы можете совершить действие магия, чтобы снова изменить свою внешность таким образом.\nЕстественное оружие. Вы отращиваете когти (рубящий урон), клыки (колющий урон), рога (дробящий урон) или копыта (дробящий урон). При нанесении урона безоружным ударом вы наносите 1к6 дробящего, колющего или рубящего урона, в зависимости от выбранного вами оружия, и вы используете модификатор заклинательной характеристики для бросков атаки и урона вместо Силы.",
    "onHigherLevel": "",
    "onHigherLevelRus": "",
    "school": "Transmutation",
    "schoolRus": "Преображения",
    "classBarbarian": "FALSE",
    "classBard": "FALSE",
    "classCleric": "FALSE",
    "classDruid": "FALSE",
    "classFighter": "FALSE",
    "classMonk": "FALSE",
    "classPaladin": "FALSE",
    "classRanger": "FALSE",
    "classRogue": "FALSE",
    "classSorcerer": "TRUE",
    "classWarlock": "FALSE",
    "classWizard": "TRUE"
},
{
    "№": "5",
    "title": "Animal Friendship",
    "titleRus": "Дружба С Животными",
    "level": "1",
    "ritual": "FALSE",
    "castingTime": "Action",
    "castingTimeRus": "Действие",
    "rangeFt": "30",
    "componentV": "TRUE",
    "componentS": "TRUE",
    "componentM": "a morsel of food",
    "componentMRus": "кусочек пищи",
    "concentration": "FALSE",
    "duration": "24 hours",
    "durationRus": "24 часа",
    "description": "Target a Beast that you can see within range. The target must succeed on a Wisdom saving throw or\nhave the Charmed condition for the duration. If you or one of your allies deals damage to the target, the spells ends.",
    "descriptionRus": "Целью заклинания становится существо с типом зверь, которое вы видите в пределах дистанции. Цель должна преуспеть в спасброске Мудрости, иначе она будет находиться под действием состояния очарованный на продолжительность действия заклинания. Если вы или один из ваших союзников наносит урон цели, то заклинание заканчивается.",
    "onHigherLevel": "You can target one additional Beast for each spell slot level above 1.",
    "onHigherLevelRus": "Вы можете выбрать одну дополнительную цель (зверя) за каждый уровень ячейки выше 1.",
    "school": "Enchantment",
    "schoolRus": "Очарования",
    "classBarbarian": "FALSE",
    "classBard": "TRUE",
    "classCleric": "FALSE",
    "classDruid": "TRUE",
    "classFighter": "FALSE",
    "classMonk": "FALSE",
    "classPaladin": "FALSE",
    "classRanger": "TRUE",
    "classRogue": "FALSE",
    "classSorcerer": "FALSE",
    "classWarlock": "FALSE",
    "classWizard": "FALSE"
},
{
    "№": "6",
    "title": "Animal Messenger",
    "titleRus": "Почтовое Животное",
    "level": "2",
    "ritual": "TRUE",
    "castingTime": "Action or Ritual",
    "castingTimeRus": "Действие или ритуал",
    "rangeFt": "30",
    "componentV": "TRUE",
    "componentS": "TRUE",
    "componentM": "a morsel of food",
    "componentMRus": "кусочек пищи",
    "concentration": "FALSE",
    "duration": "24 hours",
    "durationRus": "24 часа",
    "description": "A Tiny Beast of your choice that you can see within range must succeed on a Charisma saving throw, or it attempts to deliver a message for you (if the target's Challenge Rating isn't 0, it automatically succeeds). You specify a location you have visited and a recipient who matches a general description, such as \"\"a person dressed in the uniform of the town guard\"\" or \"\"a red-haired dwarf wearing a pointed hat.\"\" You also communicate a message of up to twenty-five words. The Beast travels for the duration toward the specified location, covering about 25 miles per 24 hours or 50 miles if the Beast can fly.\nWhen the Beast arrives, it delivers your message to the creature that you described, mimicking your communication. If the Beast doesn't reach its destination before the spell ends, the message is lost, and the Beast returns to where you cast the spell.",
    "descriptionRus": "Крохотный зверь на ваш выбор, которого вы видите в пределах дистанции, должен преуспеть в спасброске Харизмы, иначе он попытается доставить ваше сообщение (если ПО цели не 0, то она автоматически преуспевает в спасброске). Вы указываете место, которое когда-то уже посещали, и получателя, описывая его признаки, такие как «персона в униформе городской стражи» или «рыжий дварф в остроконечной шляпе». Вы также произносите сообщение длиной не более 25 слов. Зверь в течение длительности заклинания двигается в указанное место, покрывая примерно 50 миль за 24 часа при полёте или 25 миль при других видах перемещения.\nПрибыв на место, зверь передаёт ваше сообщение описанному вами существу, изображая звук вашего голоса. Если зверь не достигнет места до окончания действия заклинания, то сообщение будет утеряно, а зверь начнёт возвращаться к тому месту, где вы наложили на него заклинание.",
    "onHigherLevel": "The spell's duration increases by 48 hours for each spell slot level above 2.",
    "onHigherLevelRus": "Длительность увеличивается на 48 часов за каждый уровень ячейки выше 2.",
    "school": "Enchantment",
    "schoolRus": "Очарования",
    "classBarbarian": "FALSE",
    "classBard": "TRUE",
    "classCleric": "FALSE",
    "classDruid": "TRUE",
    "classFighter": "FALSE",
    "classMonk": "FALSE",
    "classPaladin": "FALSE",
    "classRanger": "TRUE",
    "classRogue": "FALSE",
    "classSorcerer": "FALSE",
    "classWarlock": "FALSE",
    "classWizard": "FALSE"
}
];

const DndDataUploader = () => {
  // Функция для загрузки данных в Firebase
  const uploadData = async () => {
    const spellsCollection = collection(db, "spells");
    try {
      for (const spell of spells) {
        await addDoc(spellsCollection, spell);
        console.log(`Заклинание "${spell.title}" добавлено в базу данных!`);
      }
    } catch (error) {
      console.error("Ошибка при добавлении данных: ", error);
    }
  };

  return (
    <div>
      <p>Загрузить данные о заклинаниях</p>
      <button onClick={uploadData}>Загрузить заклинания в Firestore</button>
    </div>
  );
};

export default DndDataUploader;
